use patient_manager_app::shared::{bindings_path, create_specta_builder};
use specta_typescript::{BigIntExportBehavior, Typescript};

/// Generate TypeScript bindings for CI/release builds
///
/// This binary generates the same bindings.ts file that main.rs generates in debug mode.
/// Use this for CI pipelines and release builds where you want to pre-generate types
/// without running the full Tauri application.
///
/// Usage: cargo run --bin generate_bindings
fn main() {
    println!("Generating TypeScript bindings...");

    let output_path = bindings_path();

    // Use the same builder configuration as main.rs
    let builder = create_specta_builder();

    // Export TypeScript bindings to src/bindings.ts
    let ts_config = Typescript::default()
        .bigint(BigIntExportBehavior::Number)
        .header(
            "// @ts-nocheck\n/* eslint-disable */\n// Generated by Specta - do not edit manually\n",
        );
    builder
        .export(ts_config, &output_path)
        .expect("Failed to export TypeScript bindings");

    println!(
        "✅ TypeScript bindings generated successfully: {}",
        output_path.display()
    );
}
