use crate::{
    context::{bank, fund, patient, procedure},
    core::{health, logger},
    use_cases::{
        bank_statement_reconciliation, excel_import, fund_payment_reconciliation,
        procedure_orchestration as use_cases_procedure,
    },
};

/// create the Specta builder for standard and generate_bindings
pub fn create_specta_builder() -> tauri_specta::Builder<tauri::Wry> {
    tauri_specta::Builder::<tauri::Wry>::new()
        .typ::<fund::AffiliatedFund>()
        .typ::<patient::Patient>()
        .typ::<procedure::Procedure>()
        .typ::<procedure::ProcedureType>()
        .typ::<fund::FundPaymentGroup>()
        .typ::<fund::FundPaymentLine>()
        .typ::<bank::BankTransfer>()
        .typ::<bank::BankTransferType>()
        .typ::<bank::BankAccount>()
        .typ::<patient::PatientCandidate>()
        .typ::<patient::PatientValidationStatus>()
        .typ::<patient::PatientValidationResult>()
        .typ::<patient::ValidateBatchPatientsResponse>()
        .typ::<patient::CreateBatchPatientsResponse>()
        .typ::<fund::FundCandidate>()
        .typ::<fund::FundValidationStatus>()
        .typ::<fund::FundValidationResult>()
        .typ::<fund::ValidateBatchFundsResponse>()
        .typ::<fund::CreateBatchFundsResponse>()
        .typ::<procedure::ProcedureCandidate>()
        .typ::<use_cases_procedure::ProcedureValidationStatus>()
        .typ::<use_cases_procedure::ProcedureValidationResult>()
        .typ::<use_cases_procedure::ValidateBatchProceduresResponse>()
        .typ::<use_cases_procedure::CreateBatchProceduresResponse>()
        .typ::<excel_import::ParseExcelResponse>()
        .typ::<excel_import::ImportExecutionResult>()
        .typ::<excel_import::ExcelAmountMapping>()
        .typ::<excel_import::SaveExcelAmountMappingRequest>()
        .typ::<fund_payment_reconciliation::PdfParseResult>()
        .typ::<fund_payment_reconciliation::ReconciliationResult>()
        .typ::<fund_payment_reconciliation::AnomalyType>()
        .typ::<fund_payment_reconciliation::FundPaymentGroupEditData>()
        .typ::<fund::FundPaymentGroupCandidate>()
        .typ::<fund_payment_reconciliation::FundPaymentValidationStatus>()
        .typ::<fund_payment_reconciliation::FundPaymentCandidateValidation>()
        .typ::<fund_payment_reconciliation::ReconcileAndCandidatesResponse>()
        .typ::<fund_payment_reconciliation::CreateFundPaymentFromCandidatesRequest>()
        .typ::<fund_payment_reconciliation::AutoCorrection>()
        .typ::<fund_payment_reconciliation::CreateFundPaymentWithAutoCorrectionsRequest>()
        .typ::<fund_payment_reconciliation::NotFoundCandidate>()
        .typ::<fund_payment_reconciliation::UnreconciledProcedure>()
        .typ::<bank_statement_reconciliation::BankStatementParseResult>()
        .typ::<bank_statement_reconciliation::BankStatementCreditLine>()
        .typ::<bank_statement_reconciliation::FundLabelResolution>()
        .typ::<bank_statement_reconciliation::ResolvedCreditLine>()
        .typ::<bank_statement_reconciliation::BankStatementMatchResult>()
        .typ::<bank_statement_reconciliation::BankStatementMatch>()
        .typ::<bank_statement_reconciliation::ConfirmedMatch>()
        .typ::<bank_statement_reconciliation::SaveLabelMappingRequest>()
        .typ::<bank_statement_reconciliation::BankFundLabelMapping>()
        .typ::<bank_statement_reconciliation::BankStatementReconciliationConfig>()
        .commands(tauri_specta::collect_commands![
            patient::add_patient,
            patient::read_all_patients,
            patient::update_patient,
            patient::delete_patient,
            patient::validate_batch_patients,
            patient::create_batch_patients,
            fund::add_fund,
            fund::read_all_funds,
            fund::update_fund,
            fund::delete_fund,
            fund::validate_batch_funds,
            fund::create_batch_funds,
            use_cases_procedure::add_procedure,
            use_cases_procedure::read_all_procedures,
            use_cases_procedure::update_procedure,
            use_cases_procedure::delete_procedure,
            use_cases_procedure::validate_batch_procedures,
            use_cases_procedure::create_batch_procedures,
            use_cases_procedure::get_unpaid_procedures_by_fund,
            use_cases_procedure::read_procedures_by_ids,
            procedure::add_procedure_type,
            procedure::read_all_procedure_types,
            procedure::update_procedure_type,
            procedure::delete_procedure_type,
            excel_import::parse_excel_file,
            excel_import::execute_excel_import,
            excel_import::get_excel_amount_mappings,
            excel_import::save_excel_amount_mappings,
            fund_payment_reconciliation::extract_pdf_text,
            fund_payment_reconciliation::extract_pdf_text_from_bytes,
            fund_payment_reconciliation::parse_pdf_text,
            fund_payment_reconciliation::reconcile_pdf_procedures,
            fund_payment_reconciliation::reconcile_and_create_candidates,
            fund_payment_reconciliation::export_reconciliation_csv,
            fund_payment_reconciliation::create_fund_payment_from_candidates,
            fund_payment_reconciliation::create_fund_payment_with_auto_corrections,
            fund_payment_reconciliation::get_unreconciled_procedures_in_range,
            fund::read_all_fund_payment_groups,
            fund::delete_fund_payment_group,
            fund::create_fund_payment_group,
            fund::update_fund_payment_group_with_procedures,
            fund_payment_reconciliation::get_fund_payment_group_edit_data,
            bank::create_bank_transfer,
            bank::read_all_bank_transfers,
            bank::read_bank_transfer,
            bank::update_bank_transfer,
            bank::delete_bank_transfer,
            bank::create_bank_account,
            bank::read_all_bank_accounts,
            bank::read_bank_account,
            bank::update_bank_account,
            bank::delete_bank_account,
            bank_statement_reconciliation::parse_bank_statement,
            bank_statement_reconciliation::resolve_bank_account_from_iban,
            bank_statement_reconciliation::resolve_bank_fund_labels,
            bank_statement_reconciliation::save_bank_fund_label_mappings,
            bank_statement_reconciliation::match_bank_statement_lines,
            bank_statement_reconciliation::create_bank_transfers_from_statement,
            bank_statement_reconciliation::get_bank_statement_reconciliation_config,
            health::check_health,
            logger::log_frontend,
        ])
    //.events(tauri_specta::collect_events![Event])
}
