#!/usr/bin/env python3
"""privacy-check.py — keep patient data out of logs and out of the repository.

Three checks:

  logs   a `tracing::*!` (Rust) or `logger.*` / `console.*` (TypeScript) call
         that logs the value of an SSN, an IBAN or a patient name. A presence
         flag (`ssn.is_some()`, `!!iban`, `.len()`, `.length`) or an IBAN tail
         (`iban[iban.len() - 4..]`) is fine.
  text   a French SSN or an IBAN whose check digits are valid, in a tracked
         file, a commit message or a PR body — unless privacy-allowlist.json
         names it as synthetic.
  data   a spreadsheet, PDF, CSV or database file outside
         src-tauri/tests/fixtures/, or a fixture without its .expected.json
         partner (generated by `just regen-fixtures`).

A finding never prints the value it found: the report would leak it.

Use:
  python3 scripts/privacy-check.py                  # every tracked file
  python3 scripts/privacy-check.py --staged         # staged files (pre-commit)
  python3 scripts/privacy-check.py --message FILE   # a commit message (text only)
  python3 scripts/privacy-check.py --stdin          # any text, e.g. a PR body
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

FIXTURES = "src-tauri/tests/fixtures/"
DATA_EXTENSIONS = {".xlsx", ".xls", ".ods", ".csv", ".pdf", ".db", ".sqlite", ".sqlite3"}
ALLOWLIST = "privacy-allowlist.json"
TEXT_SKIP = {"package-lock.json", "src-tauri/Cargo.lock", ALLOWLIST}

# --- text: SSN (NIR) and IBAN with valid check digits ------------------------

SSN = re.compile(r"(?<![\dA-Za-z])([12]) ?(\d{2}) ?(0[1-9]|1[0-2]|[2-9]\d) ?(\d{2}|2[AB]) ?(\d{3}) ?(\d{3}) ?(\d{2})(?![\dA-Za-z])")
IBAN = re.compile(r"(?<![A-Za-z0-9])([A-Z]{2}\d{2}(?: ?[A-Z0-9]{4}){2,7}(?: ?[A-Z0-9]{1,3})?)(?![A-Za-z0-9])")


def ssn_is_valid(match: re.Match[str]) -> bool:
    sex, year, month, dept, commune, order, key = match.groups()
    dept = {"2A": "19", "2B": "18"}.get(dept, dept)
    number = int(sex + year + month + dept + commune + order)
    return 97 - number % 97 == int(key)


def iban_is_valid(value: str) -> bool:
    compact = value.replace(" ", "")
    rearranged = compact[4:] + compact[:4]
    return int("".join(str(int(c, 36)) for c in rearranged)) % 97 == 1


def text_findings(text: str, allowed: set[str]) -> list[tuple[int, str]]:
    findings = []
    for number, line in enumerate(text.splitlines(), 1):
        for m in SSN.finditer(line):
            if ssn_is_valid(m) and m.group(0).replace(" ", "") not in allowed:
                findings.append((number, "SSN with a valid key"))
        for m in IBAN.finditer(line):
            compact = m.group(1).replace(" ", "")
            if iban_is_valid(compact) and compact not in allowed:
                findings.append((number, f"IBAN with valid check digits (…{compact[-4:]})"))
    return findings


# --- logs: private values handed to a log call -------------------------------

RUST_CALL = re.compile(r"\b(?:tracing::)?(?:trace|debug|info|warn|error)!\s*\(")
TS_CALL = re.compile(r"\b(?:logger|console)\.(?:trace|debug|info|log|warn|error)\s*\(")
RUST_PRIVATE = re.compile(r"\b(?:\w+\.)*(?:ssn|iban|patient_name|fund_patient_name)\b|\bpatient\.name\b")
TS_PRIVATE = re.compile(r"\b(?:\w+\.)*(?:ssn|iban|patientName|fundPatientName)\b|\bpatient\.name\b")
SAFE_SUFFIX = re.compile(
    r"\s*\.\s*(?:is_some|is_none|is_empty|len)\s*\(\s*\)"  # Rust presence / size
    r"|\s*\.\s*length\b"  # TS size
    r"|\s*!==?\s*(?:null|undefined)\b"  # TS presence
    r"|\s*\["  # a slice, e.g. an IBAN tail
)


def _call_text(source: str, start: int) -> str:
    """The argument text of the call whose `(` ends at `start`, up to its matching `)`."""
    depth, i = 1, start
    while i < len(source) and depth:
        depth += {"(": 1, ")": -1}.get(source[i], 0)
        i += 1
    return source[start : i - 1]


def _strip_strings(args: str) -> str:
    """Drop string literals but keep what they interpolate (`{ssn}`, `${ssn}`)."""
    def keep_placeholders(m: re.Match[str]) -> str:
        return " ".join(re.findall(r"\$?\{([^}]*)\}", m.group(0)))
    return re.sub(r'"(?:\\.|[^"\\])*"|\'(?:\\.|[^\'\\])*\'|`(?:\\.|[^`\\])*`', keep_placeholders, args)


def log_findings(path: str, source: str) -> list[tuple[int, str]]:
    if path.endswith(".rs"):
        call, private = RUST_CALL, RUST_PRIVATE
    elif path.endswith((".ts", ".tsx")) and not path.startswith("e2e/"):
        call, private = TS_CALL, TS_PRIVATE
    else:
        return []
    findings = []
    for m in call.finditer(source):
        args = _strip_strings(_call_text(source, m.end()))
        for ref in private.finditer(args):
            after = args[ref.end() :]
            before = args[: ref.start()].rstrip()
            if SAFE_SUFFIX.match(after) or before.endswith("!"):
                continue
            if path.endswith(".rs") and re.match(r"\s*=(?!=)", after):
                continue  # a field name (`ssn = …`); its value is checked on its own
            line = source.count("\n", 0, m.start()) + 1
            findings.append((line, f"log call hands over a private value: {ref.group(0)}"))
    return findings


# --- data files ---------------------------------------------------------------


def data_findings(paths: list[str], all_paths: set[str]) -> list[tuple[str, str]]:
    findings = []
    for path in paths:
        suffix = Path(path).suffix.lower()
        if suffix not in DATA_EXTENSIONS:
            continue
        if not path.startswith(FIXTURES):
            findings.append((path, f"{suffix} file outside {FIXTURES} — presumed real data"))
        elif str(Path(path).with_suffix(".expected.json")) not in all_paths:
            findings.append((path, "fixture without its .expected.json partner — not generated by `just regen-fixtures`"))
    return findings


# --- driver -------------------------------------------------------------------


def git(*args: str) -> str:
    return subprocess.run(["git", *args], capture_output=True, text=True, check=True).stdout


def load_allowlist(root: Path) -> set[str]:
    path = root / ALLOWLIST
    if not path.exists():
        return set()
    data = json.loads(path.read_text(encoding="utf-8"))
    return {v.replace(" ", "") for v in data.get("iban", []) + data.get("ssn", [])}


def read_blob(path: str, staged: bool) -> str | None:
    try:
        raw = subprocess.run(["git", "show", f":{path}"], capture_output=True, check=True).stdout if staged else Path(path).read_bytes()
    except (OSError, subprocess.CalledProcessError):
        return None
    if b"\0" in raw[:8192]:
        return None  # binary
    return raw.decode("utf-8", errors="replace")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--staged", action="store_true", help="check the staged files")
    mode.add_argument("--message", metavar="FILE", help="check a commit message (text check only)")
    mode.add_argument("--stdin", action="store_true", help="check text read from stdin (text check only)")
    args = parser.parse_args()

    root = Path(git("rev-parse", "--show-toplevel").strip())
    allowed = load_allowlist(root)
    report: list[str] = []

    if args.message or args.stdin:
        text = sys.stdin.read() if args.stdin else Path(args.message).read_text(encoding="utf-8", errors="replace")
        label = "stdin" if args.stdin else "commit message"
        report += [f"{label}:{n}: {what}" for n, what in text_findings(text, allowed)]
    else:
        import os

        os.chdir(root)
        all_paths = set(git("ls-files").splitlines())
        paths = git("diff", "--cached", "--name-only", "--diff-filter=ACMR").splitlines() if args.staged else sorted(all_paths)
        report += [f"{p}: {what}" for p, what in data_findings(paths, all_paths)]
        for path in paths:
            if path in TEXT_SKIP:
                continue
            text = read_blob(path, args.staged)
            if text is None:
                continue
            report += [f"{path}:{n}: {what}" for n, what in text_findings(text, allowed)]
            report += [f"{path}:{n}: {what}" for n, what in log_findings(path, text)]

    if report:
        print("❌ privacy-check: patient data found", file=sys.stderr)
        for line in report:
            print(f"   {line}", file=sys.stderr)
        print(f"   Synthetic test values go in {ALLOWLIST}; real data never enters the repository.", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    import usage_log

    usage_log.start()
    sys.exit(main())
