// Prevents additional console window on Windows in release
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use patient_manager_app::initialize_app;
use patient_manager_app::shared::create_specta_builder;
#[cfg(debug_assertions)]
use specta_typescript::{BigIntExportBehavior, Typescript};

fn main() {
    // Capture panics to both stderr and the tracing log file. Critical on
    // Windows release builds where windows_subsystem=windows hides default
    // panic output, leaving silent crashes with no diagnostic trail.
    std::panic::set_hook(Box::new(|info| {
        eprintln!("PANIC: {info}");
        tracing::error!(target: "backend", panic = %info, "Application panic");
    }));

    // Create tauri-specta builder for type-safe bindings
    let builder = create_specta_builder();

    // Export TypeScript bindings in debug mode
    #[cfg(debug_assertions)]
    {
        let ts_config = Typescript::default()
            .bigint(BigIntExportBehavior::Number)
            .header(
            "// @ts-nocheck\n/* eslint-disable */\n// Generated by Specta - do not edit manually\n",
        );
        builder
            .export(ts_config, "../src/bindings.ts")
            .expect("Failed to export typescript bindings");
    }

    tauri::Builder::default()
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_window_state::Builder::new().build())
        .plugin(tauri_plugin_updater::Builder::new().build())
        .plugin(tauri_plugin_process::init())
        .plugin(tauri_plugin_opener::init())
        .setup(|app| {
            let handle = app.handle().clone();
            // Block until initialization completes to avoid race conditions
            tauri::async_runtime::block_on(async {
                initialize_app(&handle)
                    .await
                    .expect("Failed to initialize application");
            });
            Ok(())
        })
        .invoke_handler(builder.invoke_handler())
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
