// @ts-nocheck
/* eslint-disable */
// Generated by Specta - do not edit manually

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Tauri command: Add a new patient
 */
async addPatient(name: string | null, ssn: string | null) : Promise<Result<Patient, PatientError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_patient", { name, ssn }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Read all patients
 */
async readAllPatients() : Promise<Result<Patient[], PatientError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_all_patients") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Update an existing patient
 */
async updatePatient(patient: Patient) : Promise<Result<Patient, PatientError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_patient", { patient }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Delete a patient
 */
async deletePatient(id: string) : Promise<Result<null, PatientError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_patient", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Validate batch of patient candidates
 */
async validateBatchPatients(patients: PatientCandidate[]) : Promise<Result<ValidateBatchPatientsResponse, PatientError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_batch_patients", { patients }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Create batch of patients
 */
async createBatchPatients(patients: PatientCandidate[]) : Promise<Result<CreateBatchPatientsResponse, PatientError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_batch_patients", { patients }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Add a new affiliated fund
 */
async addFund(fundIdentifier: string, fundName: string) : Promise<Result<Fund, FundError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_fund", { fundIdentifier, fundName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Read all affiliated funds
 */
async readAllFunds() : Promise<Result<Fund[], FundError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_all_funds") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Update an existing affiliated fund
 */
async updateFund(fund: Fund) : Promise<Result<Fund, FundError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_fund", { fund }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Delete an affiliated fund
 */
async deleteFund(id: string) : Promise<Result<null, FundError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_fund", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Validate batch of fund candidates
 */
async validateBatchFunds(funds: FundCandidate[]) : Promise<Result<ValidateBatchFundsResponse, FundError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_batch_funds", { funds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Create batch of funds
 */
async createBatchFunds(funds: FundCandidate[]) : Promise<Result<CreateBatchFundsResponse, FundError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_batch_funds", { funds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Add a new healthcare procedure
 */
async addProcedure(patientId: string, fundId: string | null, procedureTypeId: string, procedureDate: string, billedAmount: number) : Promise<Result<Procedure, ProcedureOrchestrationError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_procedure", { patientId, fundId, procedureTypeId, procedureDate, billedAmount }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Read all procedures
 */
async readAllProcedures() : Promise<Result<Procedure[], ProcedureOrchestrationError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_all_procedures") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Update an existing procedure
 */
async updateProcedure(raw: RawProcedure) : Promise<Result<Procedure, ProcedureOrchestrationError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_procedure", { raw }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Delete a procedure
 */
async deleteProcedure(id: string) : Promise<Result<null, ProcedureOrchestrationError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_procedure", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Validate batch of procedure candidates
 */
async validateBatchProcedures(procedures: ProcedureCandidate[]) : Promise<Result<ValidateBatchProceduresResponse, ProcedureOrchestrationError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_batch_procedures", { procedures }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Create batch of procedures
 */
async createBatchProcedures(procedures: ProcedureCandidate[]) : Promise<Result<CreateBatchProceduresResponse, ProcedureOrchestrationError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_batch_procedures", { procedures }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Get unpaid procedures by fund
 */
async getUnpaidProceduresByFund(fundId: string) : Promise<Result<Procedure[], ProcedureOrchestrationError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_unpaid_procedures_by_fund", { fundId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Get procedures by their IDs
 */
async readProceduresByIds(ids: string[]) : Promise<Result<Procedure[], ProcedureOrchestrationError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_procedures_by_ids", { ids }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Add a new procedure type
 */
async addProcedureType(name: string, defaultAmount: number, category: string | null) : Promise<Result<ProcedureType, ProcedureError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_procedure_type", { name, defaultAmount, category }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Read all procedure types
 */
async readAllProcedureTypes() : Promise<Result<ProcedureType[], ProcedureError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_all_procedure_types") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Update an existing procedure type
 */
async updateProcedureType(raw: RawProcedureType) : Promise<Result<ProcedureType, ProcedureError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_procedure_type", { raw }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Delete a procedure type
 */
async deleteProcedureType(id: string) : Promise<Result<null, ProcedureError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_procedure_type", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Parse Excel file (preview step — no DB writes)
 */
async parseExcelFile(filePath: string) : Promise<Result<ParseExcelResponse, ExcelImportError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("parse_excel_file", { filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Execute Excel import (creates patients, funds, and procedures)
 * 
 * `parsed_data` must be the exact response from `parse_excel_file` — do NOT re-parse,
 * because `procedure_type_tmp_id` UUIDs are generated randomly and must match the mapping.
 * 
 * `procedure_type_mapping` maps `procedure_type_tmp_id → procedure_type_id` as selected
 * by the user in the type-mapping UI step.
 */
async executeExcelImport(parsedData: ParseExcelResponse, procedureTypeMapping: Partial<{ [key in string]: string }>, selectedSheets: string[]) : Promise<Result<ImportExecutionResult, ExcelImportError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("execute_excel_import", { parsedData, procedureTypeMapping, selectedSheets }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Return all saved Excel amount → procedure type mappings
 */
async getExcelAmountMappings() : Promise<Result<ExcelAmountMapping[], ExcelImportError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_excel_amount_mappings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Save (upsert) Excel amount → procedure type mappings
 */
async saveExcelAmountMappings(mappings: SaveExcelAmountMappingRequest[]) : Promise<Result<null, ExcelImportError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_excel_amount_mappings", { mappings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Handler for PDF text extraction from file path
 */
async extractPdfText(filePath: string) : Promise<Result<string, FundPaymentReconciliationError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("extract_pdf_text", { filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Handler for parsing extracted PDF text into structured procedure groups.
 * Normalization (French date parsing) happens here — lines with unparseable
 * dates are counted as unparsed rather than propagating errors.
 */
async parsePdfText(text: string) : Promise<PdfParseResult> {
    return await TAURI_INVOKE("parse_pdf_text", { text });
},
/**
 * Handler for reconciling PDF procedures with database
 */
async reconcilePdfProcedures(parseResult: PdfParseResult) : Promise<Result<ReconciliationResult, FundPaymentReconciliationError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reconcile_pdf_procedures", { parseResult }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Handler for complete reconciliation workflow: reconcile PDF and group into candidates
 */
async reconcileAndCreateCandidates(parseResult: PdfParseResult) : Promise<Result<ReconcileAndCandidatesResponse, FundPaymentReconciliationError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reconcile_and_create_candidates", { parseResult }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Handler for creating fund payment groups from validated reconciliation candidates
 */
async createFundPaymentFromCandidates(request: CreateFundPaymentFromCandidatesRequest) : Promise<Result<FundPaymentGroup[], FundPaymentReconciliationError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_fund_payment_from_candidates", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Handler for creating fund payment groups with auto-corrections for anomalies
 */
async createFundPaymentWithAutoCorrections(request: CreateFundPaymentWithAutoCorrectionsRequest) : Promise<Result<FundPaymentGroup[], FundPaymentReconciliationError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_fund_payment_with_auto_corrections", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Handler for getting all unreconciled procedures in a date range (for post-reconciliation report)
 */
async getUnreconciledProceduresInRange(startDate: string, endDate: string) : Promise<Result<UnreconciledProcedure[], FundPaymentReconciliationError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_unreconciled_procedures_in_range", { startDate, endDate }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Read all fund payment groups
 * 
 * `is_locked` is derived at restore time from the persisted
 * `FundPaymentGroupStatus` (BankPaid → locked).
 */
async readAllFundPaymentGroups() : Promise<Result<FundPaymentGroup[], FundError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_all_fund_payment_groups") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Delete a fund payment group with procedure cleanup
 * 
 * Deletes the group, its lines, and resets associated procedures
 * (status → Created, clears confirmed_payment_date and paid_amount).
 * REF-240: Rejects deletion if the group belongs to an overpayment refund cascade.
 */
async deleteFundPaymentGroup(groupId: string) : Promise<Result<null, FundPaymentManualManagementError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_fund_payment_group", { groupId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Create a fund payment group from manual UI selection
 * 
 * Calculates total_amount from procedure amounts and sets procedures to Reconciled.
 */
async createFundPaymentGroup(fundId: string, paymentDate: string, procedureIds: string[]) : Promise<Result<FundPaymentGroup, FundPaymentManualManagementError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_fund_payment_group", { fundId, paymentDate, procedureIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Update a fund payment group with new procedures
 * 
 * Handles add/remove procedure logic via orchestrator:
 * - Removed procedures → reset to Created
 * - Added procedures → set to Reconciled
 * - Recalculates total_amount
 * - Rejects if any procedure is bank-reconciled (FundPaid/PartiallyFundPaid)
 */
async updateFundPaymentGroupWithProcedures(groupId: string, paymentDate: string, procedureIds: string[]) : Promise<Result<FundPaymentGroup, FundPaymentManualManagementError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_fund_payment_group_with_procedures", { groupId, paymentDate, procedureIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Get edit data for a fund payment group
 * 
 * Returns two classified lists server-side so the frontend only handles display:
 * - `current_procedures`: in the group (Reconciled / PartiallyReconciled)
 * - `available_procedures`: Created procedures for the same fund, not in the group
 */
async getFundPaymentGroupEditData(groupId: string, fundId: string) : Promise<Result<FundPaymentGroupEditData, FundPaymentManualManagementError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_fund_payment_group_edit_data", { groupId, fundId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Create a new bank transfer (bare — links managed by bank_manual_match use_case)
 */
async createBankTransfer(transferDate: string, amount: number, transferType: BankEntryType, bankAccountId: string) : Promise<Result<BankEntry, BankError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_bank_transfer", { transferDate, amount, transferType, bankAccountId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Read all bank transfers with account info
 */
async readAllBankTransfers() : Promise<Result<BankEntry[], BankError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_all_bank_transfers") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Read a single bank transfer with account info
 */
async readBankTransfer(id: string) : Promise<Result<BankEntry | null, BankError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_bank_transfer", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Update an existing bank transfer
 */
async updateBankTransfer(transfer: BankEntry) : Promise<Result<BankEntry, BankError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_bank_transfer", { transfer }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Delete a bank transfer
 */
async deleteBankTransfer(id: string) : Promise<Result<null, BankError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_bank_transfer", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Create a new bank account
 */
async createBankAccount(name: string, iban: string | null) : Promise<Result<BankAccount, BankError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_bank_account", { name, iban }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Read all bank accounts
 */
async readAllBankAccounts() : Promise<Result<BankAccount[], BankError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_all_bank_accounts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Update a bank account
 */
async updateBankAccount(id: string, name: string, iban: string | null) : Promise<Result<BankAccount, BankError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_bank_account", { id, name, iban }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Delete a bank account
 */
async deleteBankAccount(id: string) : Promise<Result<null, BankError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_bank_account", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Returns the ID of the default cash account.
 * Used by the frontend to auto-assign the account for CASH transfers (R13).
 */
async getCashBankAccountId() : Promise<string> {
    return await TAURI_INVOKE("get_cash_bank_account_id");
},
/**
 * Parse a bank statement PDF and return structured data
 */
async parseBankStatement(filePath: string) : Promise<Result<BankStatementParseResult, BankStatementReconciliationError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("parse_bank_statement", { filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resolve a bank account from IBAN
 */
async resolveBankAccountFromIban(iban: string) : Promise<Result<BankAccount | null, BankStatementReconciliationError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_bank_account_from_iban", { iban }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resolve fund labels for a bank account
 */
async resolveBankFundLabels(bankAccountId: string, labels: string[]) : Promise<Result<FundLabelResolution[], BankStatementReconciliationError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_bank_fund_labels", { bankAccountId, labels }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save confirmed fund label mappings
 */
async saveBankFundLabelMappings(bankAccountId: string, mappings: SaveLabelMappingRequest[]) : Promise<Result<null, BankStatementReconciliationError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_bank_fund_label_mappings", { bankAccountId, mappings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Match resolved credit lines against unsettled fund payment groups
 */
async matchBankStatementLines(resolvedLines: ResolvedCreditLine[]) : Promise<Result<BankStatementMatchResult, BankStatementReconciliationError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("match_bank_statement_lines", { resolvedLines }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create bank transfers from confirmed matches
 */
async createBankTransfersFromStatement(bankAccountId: string, confirmedMatches: ConfirmedMatch[]) : Promise<Result<number, BankStatementReconciliationError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_bank_transfers_from_statement", { bankAccountId, confirmedMatches }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get bank statement reconciliation configuration
 */
async getBankStatementReconciliationConfig() : Promise<BankStatementReconciliationConfig> {
    return await TAURI_INVOKE("get_bank_statement_reconciliation_config");
},
/**
 * R6 — Return Active fund payment groups within the 7-day window of transfer_date.
 */
async getUnsettledFundGroups(transferDate: string) : Promise<Result<FundGroupCandidate[], BankManualMatchError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_unsettled_fund_groups", { transferDate }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * R12 — Return all Active fund payment groups (no date constraint).
 */
async getAllUnsettledFundGroups() : Promise<Result<FundGroupCandidate[], BankManualMatchError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_all_unsettled_fund_groups") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * R7 — Create a FUND bank transfer linked to the given group IDs.
 */
async createFundTransfer(bankAccountId: string, transferDate: string, groupIds: string[]) : Promise<Result<BankManualMatchResult, BankManualMatchError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_fund_transfer", { bankAccountId, transferDate, groupIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * R9 — Update a FUND transfer: change date and/or linked groups.
 */
async updateFundTransfer(transferId: string, newTransferDate: string, newGroupIds: string[]) : Promise<Result<BankManualMatchResult, BankManualMatchError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_fund_transfer", { transferId, newTransferDate, newGroupIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * R8 — Delete a FUND transfer: revert linked groups to Active, hard-delete transfer.
 */
async deleteFundTransfer(transferId: string) : Promise<Result<null, BankManualMatchError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_fund_transfer", { transferId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * R14 — Return CREATED procedures within the 7-day window of payment_date.
 */
async getEligibleProceduresForDirectPayment(paymentDate: string) : Promise<Result<DirectPaymentProcedureCandidate[], BankManualMatchError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_eligible_procedures_for_direct_payment", { paymentDate }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * R20 — Return all CREATED procedures (no date constraint).
 */
async getAllEligibleProceduresForDirectPayment() : Promise<Result<DirectPaymentProcedureCandidate[], BankManualMatchError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_all_eligible_procedures_for_direct_payment") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * R15 — Create a direct payment transfer linked to the given procedure IDs.
 */
async createDirectTransfer(bankAccountId: string, transferDate: string, transferType: BankEntryType, procedureIds: string[]) : Promise<Result<BankManualMatchResult, BankManualMatchError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_direct_transfer", { bankAccountId, transferDate, transferType, procedureIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * R17 — Update a direct transfer: change date and/or linked procedures.
 */
async updateDirectTransfer(transferId: string, newTransferDate: string, newProcedureIds: string[]) : Promise<Result<BankManualMatchResult, BankManualMatchError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_direct_transfer", { transferId, newTransferDate, newProcedureIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * R16 — Delete a direct transfer: revert procedures to Created, hard-delete transfer.
 */
async deleteDirectTransfer(transferId: string) : Promise<Result<null, BankManualMatchError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_direct_transfer", { transferId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return the fund group IDs linked to a FUND transfer.
 */
async getTransferFundGroupIds(transferId: string) : Promise<Result<string[], BankManualMatchError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_transfer_fund_group_ids", { transferId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return the procedure IDs linked to a direct payment transfer.
 */
async getTransferProcedureIds(transferId: string) : Promise<Result<string[], BankManualMatchError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_transfer_procedure_ids", { transferId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * R21 — Return fund group candidates by IDs for the edit modal (groups are BankPaid).
 */
async getFundGroupsByIds(groupIds: string[]) : Promise<Result<FundGroupCandidate[], BankManualMatchError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_fund_groups_by_ids", { groupIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * R21 — Return procedure candidates by IDs for the edit modal (procedures are DirectlyPaid).
 */
async getProceduresByIds(procedureIds: string[]) : Promise<Result<DirectPaymentProcedureCandidate[], BankManualMatchError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_procedures_by_ids", { procedureIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Exports the active database to the given destination path as a gzip-compressed
 * SQLite file (R7, R8). The path is obtained from a native save-file dialog on
 * the frontend.
 * 
 * The frontend-supplied `dest_path` is validated as a new file in an existing
 * directory under the user's home, with a `.gz` extension — a crafted IPC
 * call that bypasses the save dialog cannot reach the filesystem layer with
 * an unrestricted path.
 */
async exportDatabase(destPath: string) : Promise<Result<null, DbBackupError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_database", { destPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Decompresses, validates, and stages a backup file as a pending import (R9, R10).
 * The replacement takes effect on the next application startup.
 * The frontend is responsible for relaunching the app after this command succeeds (R6).
 * 
 * The frontend-supplied `source_path` is validated as an existing regular
 * file under the user's home with a `.gz` extension — a crafted IPC call
 * cannot trick the importer into reading arbitrary files.
 */
async importDatabase(sourcePath: string) : Promise<Result<null, DbBackupError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_database", { sourcePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async logFrontend(level: string, message: string) : Promise<void> {
    await TAURI_INVOKE("log_frontend", { level, message });
},
/**
 * REF-050/REF-090-REF-160 — Create an overpayment refund for the given source procedure.
 */
async createOverpayment(request: CreateOverpaymentRequest) : Promise<Result<null, OverpaymentError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_overpayment", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * REF-210 — Cancel an overpayment refund (reverse creation cascade).
 */
async cancelOverpayment(request: CancelOverpaymentRequest) : Promise<Result<null, OverpaymentError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_overpayment", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * REF-200 — Fetch ProcedureRefund by source_procedure_id.
 * Used by the OverpaymentRefund modal to resolve source_procedure_id before cancel.
 */
async getProcedureRefundBySource(sourceProcedureId: string) : Promise<Result<ProcedureRefundInfo | null, OverpaymentError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_procedure_refund_by_source", { sourceProcedureId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * REF-200 — Fetch ProcedureRefund by refund_procedure_id.
 * Used by the OverpaymentRefund modal to resolve source_procedure_id before cancel
 * (the modal only holds the refund procedure's own ID).
 */
async getProcedureRefundByRefundProcedure(refundProcedureId: string) : Promise<Result<ProcedureRefundInfo | null, OverpaymentError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_procedure_refund_by_refund_procedure", { refundProcedureId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Generate the post-reconciliation report as a PDF byte stream.
 * 
 * FPR-011, FPR-013, FPR-020, FPR-021, FPR-022, FPR-030 to FPR-042.
 * 
 * The request must already carry every pre-resolved string the renderer
 * will place: translated labels, formatted dates, formatted currency
 * values, and the per-correction joined row strings. The backend performs
 * no database lookup, no translation, and no formatting (FPR-013, FPR-021).
 */
async generateFundReconciliationReportPdf(request: ReportGenerationRequest) : Promise<Result<number[], ReportPdfError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_fund_reconciliation_report_pdf", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Generate the report, save it to the user's Downloads directory under the
 * supplied filename, and launch it in the system default PDF viewer.
 * 
 * FPR-015, FPR-016. Returns the absolute path of the written file so the
 * frontend can surface its name in a confirmation toast.
 * 
 * Filename safety: the caller-supplied `filename` is treated as a leaf name
 * only — it MUST contain no path separators, no `..` segment, must end in
 * `.pdf`, and must fit within [`FILENAME_MAX_LEN`]. The destination
 * directory is fixed to the platform Downloads folder; no user-supplied
 * path component reaches the filesystem.
 * 
 * Collision handling: if a same-named file already exists, a ` (N)` suffix
 * is appended before the extension (`name.pdf` → `name (1).pdf` → …) so
 * re-exporting the same report never silently overwrites a prior one.
 */
async exportAndOpenFundReconciliationReportPdf(request: ReportGenerationRequest, filename: string) : Promise<Result<string, ReportPdfError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_and_open_fund_reconciliation_report_pdf", { request, filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Type of detected anomaly
 */
export type AnomalyType = 
/**
 * Fund in PDF differs from fund in database
 */
"FundMismatch" | 
/**
 * Amount in PDF differs from amount in database
 */
"AmountMismatch" | 
/**
 * Procedure date is off by 1 day (matched via date-1 pass)
 */
"DateMismatch"
/**
 * Auto-correction action for an anomaly
 */
export type AutoCorrection = 
/**
 * Update procedure amount to PDF amount
 */
{ AmountMismatch: { procedure_id: string; pdf_amount: number } } | 
/**
 * Update procedure fund to PDF fund
 */
{ FundMismatch: { procedure_id: string; pdf_fund_label: string } } | 
/**
 * Update procedure date to PDF date
 */
{ DateMismatch: { procedure_id: string; pdf_date: string } } | 
/**
 * Create new procedure from PDF line (creates patient if not found)
 */
{ CreateProcedure: { ssn: string; patient_name: string; procedure_date: string; payment_date: string; billed_amount: number; pdf_fund_label: string } } | 
/**
 * Link existing procedure to fund payment and correct patient SSN from PDF
 */
{ LinkProcedure: { procedure_id: string; pdf_ssn: string; pdf_fund_label: string; payment_date: string } } | 
/**
 * Contest the fund payment amount: keep billed_amount unchanged,
 * set paid_amount to the PDF amount (what the fund claims to have paid).
 * Sets payment_status to PartiallyReconciled.
 */
{ ContestAmount: { procedure_id: string; 
/**
 * Amount actually paid by the fund (from PDF), in thousandths of a euro
 */
paid_amount: number } }
/**
 * Bank Account aggregate root
 * Represents a bank account used for transfers
 */
export type BankAccount = { name: string; iban: string | null; 
/**
 * Metadata - not a domain property
 */
id: string }
/**
 * BankEntry aggregate root
 * Represents a bank transfer (FUND) or direct payment (CHECK/CREDIT_CARD/CASH).
 * Links to fund payment groups or procedures are stored in junction tables.
 */
export type BankEntry = { id: string; transfer_date: string; amount: number; transfer_type: BankEntryType; bank_account: BankAccount }
/**
 * Payment type for bank transfers
 * 
 * Note: `OutgoingWire` is exclusively created via the overpayment refund flow (REF-080).
 * It must NOT be accepted in the bank statement manual-match UI.
 */
export type BankEntryType = "FUND_WIRE" | "PATIENT_CHECK" | "PATIENT_CREDIT_CARD" | "PATIENT_CASH" | 
/**
 * Outgoing wire refund — only creatable via the overpayment flow (REF-080, REF-110).
 * Carries a negative amount to represent money returned to a fund.
 */
"FUND_OUTGOING_WIRE"
/**
 * Errors raised by the Bank bounded context.
 * 
 * Wire shape: each variant serializes as `{ "code": "<VariantName>", ... }`
 * (struct fields when present). The frontend narrows on `code` per F27.
 */
export type BankError = 
/**
 * `BankAccount::validate` rejected an empty name.
 */
{ code: "BankAccountNameEmpty" } | 
/**
 * `BankEntryType::ensure_not_refund_only_variant` rejected the
 * `FundOutgoingWire` variant (REF-080: refund-only path).
 */
{ code: "RefundOnlyVariantRejected" } | 
/**
 * `BankEntry::validate` rejected an amount ≤ 0.
 */
{ code: "AmountNotPositive" } | 
/**
 * `BankEntry::new` / `with_id` rejected a transfer_date that does not
 * parse as `YYYY-MM-DD`.
 */
{ code: "InvalidTransferDateFormat" } | 
/**
 * `BankAccountService::create_account` / `update_account` enforced
 * IBAN uniqueness (R5) — another row already holds the IBAN.
 */
{ code: "IbanAlreadyUsed" } | 
/**
 * `BankAccountService::read_account` / `update_account` lookup returned
 * no row.
 */
{ code: "BankAccountNotFound"; bank_account_id: string } | 
/**
 * `BankAccountService::update_account` / `delete_account` rejected
 * mutation of the protected cash account.
 */
{ code: "ProtectedCashAccount" } | 
/**
 * `BankEntryService::update_transfer` lookup returned no row.
 */
{ code: "TransferNotFound"; bank_transfer_id: string } | 
/**
 * Repository / sqlx-level failure. Underlying error is logged at the
 * call site via `tracing::error!`; the wire surface carries no detail.
 */
{ code: "DatabaseError" }
/**
 * A mapping between a bank label (as seen on statements) and a fund
 */
export type BankFundLabelMapping = { id: string; bank_account_id: string; bank_label: string; fund_id: string | null }
/**
 * Composite error for the manual bank-transfer matching use case.
 * 
 * Holds ONLY `#[from]` wrappers — the three bounded-context enums it
 * orchestrates (bank + fund + procedure) plus the use-case task sub-enum. Each
 * carries its own `#[serde(tag = "code")]`, so the untagged composite flattens
 * to a single `{ "code": "...", ... }` payload on the wire.
 * 
 * Each BC enum emits `{ "code": "DatabaseError" }` for its infra catch-all; the
 * collision is intentional — the frontend maps the single code to one message.
 * See `fund_payment_manual_management/error.rs` for the same precedent.
 */
export type BankManualMatchError = BankError | FundError | ProcedureError | BankManualMatchTask
/**
 * Result of creating a bank transfer with links
 */
export type BankManualMatchResult = { transfer_id: string; linked_count: number }
/**
 * Use-case-specific guards for manual bank-transfer matching.
 * 
 * The single guard that does NOT belong to any one bounded context: R4's
 * immutable-type cross-check, which rejects driving a FUND transfer through a
 * direct-payment command (or vice versa). Tagged with `code` so the variant
 * emits `{ "code": "WrongTransferType" }` on the wire.
 */
export type BankManualMatchTask = 
/**
 * R4 — the targeted transfer's type does not match the command: a FUND
 * transfer was passed to a direct-payment operation, or a direct transfer
 * to a FUND operation. The matching-typed command must be used instead.
 */
{ code: "WrongTransferType" }
/**
 * A single credit line from a bank statement (VIR SEPA only)
 */
export type BankStatementCreditLine = { 
/**
 * ISO date YYYY-MM-DD
 */
date: string; 
/**
 * Fund label extracted from VIR SEPA, e.g. "CPAM93", "MUTUELLEGENERALEEDUCATIONNAT"
 */
label: string; 
/**
 * Credit amount in thousandths of a euro (1 € = 1000)
 */
amount: number }
/**
 * A match between a bank statement credit line and a FundPaymentGroup
 */
export type BankStatementMatch = { credit_line: ResolvedCreditLine; group_id: string; group_fund_id: string; group_payment_date: string; group_total_amount: number }
/**
 * Result of matching bank statement lines against unsettled groups
 */
export type BankStatementMatchResult = { matched: BankStatementMatch[]; unmatched_lines: ResolvedCreditLine[] }
/**
 * Result of parsing a bank statement PDF
 */
export type BankStatementParseResult = { 
/**
 * IBAN extracted from PDF header (normalized, no spaces)
 */
iban: string | null; 
/**
 * Statement period, e.g. "du 01/05/2025 au 30/05/2025"
 */
period: string | null; 
/**
 * Credit lines from VIR SEPA entries
 */
credit_lines: BankStatementCreditLine[]; 
/**
 * Sum of all credit amounts in thousandths of a euro
 */
total_credits: number; 
/**
 * Number of lines that couldn't be parsed
 */
unparsed_count: number }
/**
 * Bank statement reconciliation configuration exported to frontend
 */
export type BankStatementReconciliationConfig = { 
/**
 * Maximum date offset (days) for matching bank lines to payment groups
 */
max_date_offset_days: number }
/**
 * Composite error for the bank-statement reconciliation use case.
 * 
 * Holds ONLY `#[from]` wrappers — the two bounded-context enums it orchestrates
 * (bank + fund) plus the use-case task sub-enum. Each carries its own
 * `#[serde(tag = "code")]`, so the untagged composite flattens to a single
 * `{ "code": "...", ... }` payload on the wire.
 * 
 * Each BC enum + the Task sub-enum emit `{ "code": "DatabaseError" }` for their
 * infra catch-all; the collision is intentional — the frontend maps the single
 * code to one message.
 */
export type BankStatementReconciliationError = BankError | FundError | BankStatementReconciliationTask
/**
 * Use-case-specific guards for bank-statement reconciliation.
 * 
 * Codes that do NOT belong to any single bounded context: the PDF parse /
 * path-validation pipeline failures, the R26 "no SEPA credit lines" halt (the
 * frontend keys its dedicated guidance on this code), the confirmed-match date
 * guard, and the catch-all for the use-case-owned label-mapping repository's
 * infra failures. Tagged with `code` so each variant emits `{ "code": "..." }`.
 */
export type BankStatementReconciliationTask = 
/**
 * R26 — the parsed statement contains no actionable VIR SEPA credit lines.
 * The frontend matches on this code to show dedicated "no SEPA lines"
 * guidance instead of the generic error.
 */
{ code: "NoSepaCreditLines" } | 
/**
 * The user home directory could not be resolved, so the upload path cannot
 * be sandbox-validated.
 */
{ code: "HomeDirUnresolved" } | 
/**
 * The supplied statement path failed sandbox validation (outside the
 * allowed root, wrong extension, missing file, traversal). Detail is logged
 * at the call site; the wire carries no path.
 */
{ code: "PathRejected" } | 
/**
 * PDF text extraction failed after the path passed validation (corrupt or
 * unreadable PDF).
 */
{ code: "PdfExtractionFailed" } | 
/**
 * A confirmed match carried a date that does not parse as `YYYY-MM-DD`.
 */
{ code: "InvalidConfirmedMatchDate" } | 
/**
 * Failure from the use-case-owned label-mapping repository. Logged at the
 * call site via `tracing::error!`; the wire carries no detail.
 */
{ code: "DatabaseError" }
/**
 * Request DTO for cancelling an overpayment (REF-210).
 * The frontend always passes the source_procedure_id as identifier.
 */
export type CancelOverpaymentRequest = { source_procedure_id: string }
/**
 * A confirmed match ready for bank transfer creation
 */
export type ConfirmedMatch = { group_id: string; date: string; amount: number }
/**
 * One correction group within Section 2 (FPR-041, FPR-042).
 * 
 * Frontend joins each correction's columns into a single pre-formatted string
 * before sending — the renderer treats `rows` as opaque text lines.
 */
export type CorrectionGroup = { title: string; rows: string[] }
/**
 * Complex response: created funds + temp ID mapping for import tracking
 */
export type CreateBatchFundsResponse = { funds: Fund[]; temp_id_map: Partial<{ [key in string]: string }> }
/**
 * Complex response: created patients + temp ID mapping for import tracking
 */
export type CreateBatchPatientsResponse = { patients: Patient[]; temp_id_map: Partial<{ [key in string]: string }> }
/**
 * Response DTO for procedure batch creation
 */
export type CreateBatchProceduresResponse = { procedures: Procedure[] }
/**
 * Request to create fund payment groups from validated candidates
 */
export type CreateFundPaymentFromCandidatesRequest = { 
/**
 * Validated candidates to process
 */
candidates: FundPaymentGroupCandidate[] }
/**
 * Request to create fund payment groups with auto-corrections
 */
export type CreateFundPaymentWithAutoCorrectionsRequest = { 
/**
 * Validated candidates to process
 */
candidates: FundPaymentGroupCandidate[]; 
/**
 * Auto-corrections to apply
 */
auto_corrections: AutoCorrection[] }
/**
 * Request DTO for creating an overpayment refund (REF-050 through REF-160).
 */
export type CreateOverpaymentRequest = { source_procedure_id: string; 
/**
 * ISO date string (YYYY-MM-DD) — validated against REF-030.
 */
refund_date: string; 
/**
 * Domain enum name: "CreditCard", "Check", or "OutgoingWire" (REF-060).
 */
transfer_type: string; 
/**
 * Bank account to use for the refund bank transfer (REF-070).
 */
bank_account_id: string; 
/**
 * Optional free-text reason, max 255 chars (REF-040).
 */
reason: string | null }
/**
 * Typed error for the database-backup use case.
 * 
 * `db_backup` orchestrates no bounded context — it is pure infrastructure
 * (filesystem + SQLite snapshotting) — so this is a single flat enum rather
 * than a `{UseCase}Error` composite. Tagged with `code` so each variant emits
 * `{ "code": "..." }` on the wire.
 * 
 * Variants carry no payload: the underlying `std::io` / `sqlx` detail is logged
 * at the failure site via `tracing::error!` and never crosses the wire (it can
 * leak absolute paths). The frontend maps each code to a localized message.
 */
export type DbBackupError = 
/**
 * The user's home directory could not be resolved — the allowed-root for
 * path validation is unavailable.
 */
{ code: "HomeUnresolved" } | 
/**
 * The frontend-supplied path was rejected by the secure-path validator
 * (outside the allowed root, wrong extension, or wrong file kind).
 */
{ code: "PathRejected" } | 
/**
 * Producing the compressed snapshot failed (VACUUM, gzip, or file I/O).
 */
{ code: "ExportFailed" } | 
/**
 * Staging the backup failed (decompression, file I/O, or rename).
 */
{ code: "ImportFailed" } | 
/**
 * The decompressed file is not a valid, intact SQLite database — the
 * integrity check failed. The selected file is not a usable backup.
 */
{ code: "BackupCorrupted" }
/**
 * A single DB procedure match within an issue
 */
export type DbMatch = { procedure_id: string; procedure_date: string; fund_id: string | null; amount: number | null; anomalies: AnomalyType[] }
/**
 * A procedure candidate for a direct payment (R14)
 */
export type DirectPaymentProcedureCandidate = { procedure_id: string; patient_id: string; procedure_date: string; billed_amount: number }
/**
 * A saved mapping between a procedure amount (thousandths of a euro) and a procedure type id
 */
export type ExcelAmountMapping = { amount: number; procedure_type_id: string }
/**
 * Parsed fund data from Excel Secu sheet
 */
export type ExcelFund = { temp_id: string; fund_identifier: string; fund_name: string; fund_address: string | null }
/**
 * Error surface for the Excel import use case.
 * 
 * A flat `#[serde(tag = "code")]` enum — NOT an untagged composite. The
 * excel-import contract deliberately keeps the error surface coarse: per-row
 * failures are reported in-band via `ParsingIssues` / `skipped_procedures`,
 * never as command errors, and infrastructure failures collapse to a single
 * catch-all (`ImportFailed` for execution, `DatabaseError` for the mapping
 * repo). There are no FE-meaningful bounded-context errors to wrap with
 * `#[from]`, so the use-case enum is the FE-facing type directly.
 * 
 * The frontend narrows on `code` per F27.
 */
export type ExcelImportError = 
/**
 * `parse_excel_file` — the path does not exist on disk.
 */
{ code: "FileNotFound"; path: string } | 
/**
 * `parse_excel_file` — the file exists but cannot be opened or read as an
 * xlsx workbook.
 */
{ code: "InvalidFormat" } | 
/**
 * `parse_excel_file` — the workbook opened but a required sheet could not
 * be parsed.
 */
{ code: "ParseError" } | 
/**
 * `execute_excel_import` — catch-all for infrastructure failures (repo /
 * service writes). Per the contract, all per-row failures surface via
 * `ImportExecutionResult.skipped_procedures`, so this covers only
 * infrastructure-level faults. Logged at the call site; the wire surface
 * carries no detail.
 */
{ code: "ImportFailed" } | 
/**
 * `get_excel_amount_mappings` / `save_excel_amount_mappings` — a failure
 * from the amount-mapping repository. Logged at the call site.
 */
{ code: "DatabaseError" }
/**
 * Parsed patient data from Excel Patiente sheet
 */
export type ExcelPatient = { temp_id: string; name: string; ssn: string; latest_fund: string | null }
/**
 * Parsed procedure data from Excel monthly sheets
 */
export type ExcelProcedure = { patient_temp_id: string; fund_temp_id: string | null; procedure_type_tmp_id: string; amount: number; procedure_date: string; sheet_month: string; payment_method: string | null; confirmed_payment_date: string | null; paid_amount: number | null; awaited_amount: number | null; 
/**
 * 1-based row index in the source sheet. Transport metadata — excluded
 * from codec round-trip equality per IFC-026. Populated by the parser
 * when reading; the dev generator assigns from output position.
 */
source_row: number }
/**
 * Fund aggregate root
 */
export type Fund = { fund_identifier: string; name: string; 
/**
 * Temporary ID used during batch imports to map temp_id → real_id
 * None for funds created through regular API
 * Some(uuid) for funds created via Excel import
 */
temp_id?: string | null; 
/**
 * Metadata - not a domain property
 */
id: string }
/**
 * Fund candidate for batch import - semantically different from Fund (lacks ID, created_at)
 */
export type FundCandidate = { temp_id: string; fund_identifier: string; fund_name: string }
/**
 * Errors raised by the Fund bounded context.
 * 
 * Wire shape: each variant serializes as `{ "code": "<VariantName>", ... }`
 * (struct fields when present). The frontend narrows on `code` per F27.
 */
export type FundError = 
/**
 * `Fund::validate` rejected an empty fund identifier.
 */
{ code: "FundIdentifierEmpty" } | 
/**
 * `Fund::validate` rejected an empty fund name.
 */
{ code: "FundNameEmpty" } | 
/**
 * `FundPaymentGroup::validate` rejected an empty fund_id.
 */
{ code: "FundIdEmpty" } | 
/**
 * `FundPaymentGroup::validate` rejected a non-positive total amount.
 */
{ code: "TotalAmountNotPositive" } | 
/**
 * `FundPaymentGroup::new` / `with_id` / service update path rejected
 * a payment date that does not parse as `YYYY-MM-DD`.
 */
{ code: "InvalidPaymentDateFormat" } | 
/**
 * `FundPaymentLine::validate` rejected an empty fund_payment_group_id.
 */
{ code: "FundPaymentGroupIdEmpty" } | 
/**
 * `FundPaymentLine::validate` rejected an empty procedure_id.
 */
{ code: "LineProcedureIdEmpty" } | 
/**
 * `FundPaymentGroupService` update-by-id lookup returned no row.
 */
{ code: "PaymentGroupNotFound"; fund_payment_group_id: string } | 
/**
 * Repository / sqlx-level failure. Underlying error is logged at the
 * call site via `tracing::error!`; the wire surface carries no detail.
 */
{ code: "DatabaseError" }
/**
 * A fund payment group candidate for a FUND transfer (R6)
 */
export type FundGroupCandidate = { group_id: string; fund_id: string; payment_date: string; total_amount: number }
/**
 * Resolution status for a bank statement fund label
 */
export type FundLabelResolution = { bank_label: string; 
/**
 * Fund ID if already confirmed via mapping table
 */
fund_id: string | null; 
/**
 * Suggested fund ID from heuristic matching
 */
suggested_fund_id: string | null; 
/**
 * Suggested fund name (for display)
 */
suggested_fund_name: string | null; 
/**
 * Whether this mapping is confirmed (from mapping table)
 */
is_confirmed: boolean; 
/**
 * Whether this label is explicitly rejected (not a fund payment)
 */
is_rejected: boolean }
/**
 * Validation result for a fund payment candidate
 */
export type FundPaymentCandidateValidation = { candidate: FundPaymentGroupCandidate; status: FundPaymentValidationStatus; error: string | null }
/**
 * FundPaymentGroup aggregate root
 * Represents a batch of payments from a single fund (e.g., CPAM payment run)
 */
export type FundPaymentGroup = { id: string; fund_id: string; payment_date: string; total_amount: number; lines: FundPaymentLine[]; status: FundPaymentGroupStatus; 
/**
 * Derived from status: true when BankPaid. Group cannot be edited or deleted when locked.
 */
is_locked: boolean }
/**
 * Fund payment group candidate created from PDF reconciliation data
 * Groups matched procedures by (fund_id + payment_date)
 */
export type FundPaymentGroupCandidate = { 
/**
 * Fund identifier from PDF (e.g., "CPAM n° 931")
 */
fund_label: string; 
/**
 * Payment date (serialized as ISO string YYYY-MM-DD for frontend)
 */
payment_date: string; 
/**
 * Total amount stated in PDF for this group
 */
total_amount: number; 
/**
 * List of matched procedure IDs for this group
 */
procedure_ids: string[]; 
/**
 * Sum of matched procedure amounts
 */
matched_amount: number; 
/**
 * Coverage status: is matched_amount == total_amount?
 */
is_fully_covered: boolean }
/**
 * Response for the edit modal: procedures in the group + procedures available to add
 */
export type FundPaymentGroupEditData = { 
/**
 * Procedures currently in the group (Reconciled / PartiallyReconciled)
 */
current_procedures: Procedure[]; 
/**
 * Created procedures for the same fund not yet in the group
 */
available_procedures: Procedure[] }
/**
 * Status of a fund payment group in the bank reconciliation lifecycle
 */
export type FundPaymentGroupStatus = 
/**
 * Group is active — not yet bank-reconciled, can be edited or deleted
 */
"ACTIVE" | 
/**
 * Group has been bank-reconciled — locked, cannot be edited or deleted
 */
"BANK_PAID"
/**
 * FundPaymentLine aggregate
 * Links a fund payment group to a specific procedure
 */
export type FundPaymentLine = { id: string; fund_payment_group_id: string; procedure_id: string }
/**
 * Composite error for the manual fund-payment-management use case.
 * 
 * Holds ONLY `#[from]` wrappers — the two bounded-context enums it
 * orchestrates (fund + procedure) plus the use-case task sub-enum. Each
 * carries its own `#[serde(tag = "code")]`, so the untagged composite
 * flattens to a single `{ "code": "...", ... }` payload on the wire.
 * 
 * Multiple arms can emit `{ "code": "DatabaseError" }` (each BC enum + the
 * Task sub-enum); the collision is intentional — the frontend maps the single
 * code to one message. See `fund_payment_reconciliation/error.rs` for the same
 * precedent.
 */
export type FundPaymentManualManagementError = FundError | ProcedureError | FundPaymentManualManagementTask
/**
 * Use-case-specific guards for manual fund-payment-group management.
 * 
 * Codes that do NOT belong to any single bounded context: the
 * state-dependent "group is locked by bank-reconciled procedures" guard, the
 * REF-240 refund-group protection (enforced via a cross-call into the
 * overpayment use case), and the catch-all for the overpayment cross-call's
 * infra failures. Tagged with `code` so each variant emits `{ "code": "..." }`.
 */
export type FundPaymentManualManagementTask = 
/**
 * The group contains bank-reconciled procedures (`FundPaid` /
 * `PartiallyFundPaid`); it cannot be modified or deleted (R9).
 */
{ code: "GroupLocked" } | 
/**
 * REF-240 — the group belongs to an overpayment refund cascade and can
 * only be removed by cancelling the refund, not by direct deletion.
 */
{ code: "RefundGroupProtected" } | 
/**
 * Failure from the overpayment refund-group check the delete flow performs.
 * Logged at the call site via `tracing::error!`; the wire carries no detail.
 */
{ code: "DatabaseError" }
/**
 * Composite error for the fund-payment-reconciliation use case.
 * 
 * Holds ONLY `#[from]` wrappers — the three bounded-context enums it
 * orchestrates plus the use-case task sub-enum. Each carries its own
 * `#[serde(tag = "code")]`, so the untagged composite flattens to a single
 * `{ "code": "...", ... }` payload on the wire.
 * 
 * Multiple arms can emit `{ "code": "DatabaseError" }` (each BC enum + the
 * Task sub-enum); the collision is intentional — the frontend maps the single
 * code to one message. See `procedure_orchestration/error.rs` for the same
 * precedent.
 */
export type FundPaymentReconciliationError = FundError | PatientError | ProcedureError | FundPaymentReconciliationTask
/**
 * Use-case-specific guards and catch-alls for fund-payment reconciliation.
 * 
 * Codes that do NOT belong to any single bounded context: the duplicate-batch
 * guards, the "nothing to process" guards, the wire date-range parse, the PDF
 * path-validation / extraction failures, and the catch-all for failures from
 * repositories the reconciliation service holds directly. Tagged with `code`
 * so each variant emits `{ "code": "..." }`.
 */
export type FundPaymentReconciliationTask = 
/**
 * Every candidate in the batch already exists as a fund-payment group —
 * the PDF was almost certainly already imported.
 */
{ code: "AllDuplicates"; count: number } | 
/**
 * No non-duplicate candidate remained to process.
 */
{ code: "NoValidCandidates" } | 
/**
 * No non-duplicate candidate remained after applying auto-corrections.
 */
{ code: "NoValidCandidatesAfterCorrections" } | 
/**
 * A wire date (`start_date` / `end_date`) did not parse as `YYYY-MM-DD`.
 */
{ code: "InvalidDateRange" } | 
/**
 * The supplied PDF path was rejected by the path validator.
 */
{ code: "PdfPathRejected" } | 
/**
 * Text extraction from the PDF failed.
 */
{ code: "PdfExtractionFailed" } | 
/**
 * Failure from a repository the reconciliation service holds directly.
 * Logged at the call site via `tracing::error!`; the wire surface carries
 * no detail.
 */
{ code: "DatabaseError" }
/**
 * Validation status for a fund payment candidate
 */
export type FundPaymentValidationStatus = "VALID" | "INVALID"
/**
 * Validation result wraps candidate with validation outcome
 */
export type FundValidationResult = { candidate: FundCandidate; status: FundValidationStatus; existing_id: string | null; error: string | null }
/**
 * Validation status for fund candidate
 */
export type FundValidationStatus = "VALID" | "ALREADY_EXISTS" | "INVALID"
/**
 * Result of a completed Excel import execution
 */
export type ImportExecutionResult = { patients_created: number; patients_reused: number; funds_created: number; funds_reused: number; procedures_created: number; 
/**
 * Counter of skipped procedures. Covers parse-time mapping skips (R25)
 * AND execute-time row skips (EXI-280/281); only the latter are
 * itemised in `skipped_procedures` below.
 */
procedures_skipped: number; procedures_deleted: number; 
/**
 * Months (YYYY-MM) that were blocked because they contain reconciliated/fund-payed procedures.
 */
blocked_months: string[]; 
/**
 * EXI-290 — per-row execute-time skip report (reuses the EXI-220 `SkippedRow` shape).
 * Each entry: source sheet name + 1-based row number + human-readable reason
 * authored on the backend in the user's runtime locale.
 */
skipped_procedures: SkippedRow[] }
/**
 * A normalized PDF procedure line — the ONE domain object for reconciliation.
 * 
 * All dates are NaiveDate (serialized as ISO YYYY-MM-DD via serde/specta).
 * Produced by the parser after normalization; used throughout the backend
 * and sent to the frontend via Tauri/Specta.
 */
export type NormalizedPdfLine = { 
/**
 * Unique index of the line in the original PDF
 */
line_index: number; 
/**
 * Payment date
 */
payment_date: string; 
/**
 * Invoice number
 */
invoice_number: string; 
/**
 * Fund/organism name (e.g., "CPAM n° 931")
 */
fund_name: string; 
/**
 * Patient name as registered with the fund
 */
patient_name: string; 
/**
 * Social security number (13 digits)
 */
ssn: string; 
/**
 * Nature of the act (e.g., "SF")
 */
nature: string; 
/**
 * Start date of the act or period
 */
procedure_start_date: string; 
/**
 * End date (same as start for single-date acts)
 */
procedure_end_date: string; 
/**
 * True if this line covers a period (start ≠ end)
 */
is_period: boolean; 
/**
 * Amount in thousandths of a euro (e.g. 1234 = 1.234 €)
 */
amount: number }
/**
 * A nearby unreconciled procedure candidate for manual linking
 */
export type NotFoundCandidate = { procedure_id: string; patient_name: string; ssn: string; procedure_date: string; amount: number }
/**
 * Composite error for the overpayment use case.
 * 
 * `ProcedureError` is included because the orchestrator delegates procedure
 * creation, update, and deletion to `ProcedureService`, whose typed errors
 * are already FE-meaningful (e.g. `ProcedureNotFound` when the source
 * procedure vanishes mid-flight). All other BC service failures (fund,
 * bank) collapse to `OverpaymentTask::DatabaseError`.
 * 
 * Both arms may emit `{ "code": "DatabaseError" }` — collision intentional,
 * see `docs/techdebt.md`.
 */
export type OverpaymentError = ProcedureError | OverpaymentTask
/**
 * Use-case-specific guards and catch-alls for the overpayment use case.
 * 
 * Tagged with `code` so each variant emits `{ "code": "..." }` on the wire.
 * The frontend narrows on `code` per F27.
 */
export type OverpaymentTask = 
/**
 * Source procedure not found by id (create or cancel path).
 */
{ code: "SourceProcedureNotFound"; id: string } | 
/**
 * REF-010 — source procedure status is not eligible for a refund.
 */
{ code: "SourceNotRefundable" } | 
/**
 * REF-030 — refund_date is malformed, in the future, or before the
 * source procedure's confirmed_payment_date.
 */
{ code: "InvalidRefundDate" } | 
/**
 * REF-040 — reason string exceeds 255 characters.
 */
{ code: "ReasonTooLong" } | 
/**
 * REF-060 — transfer_type is not accepted for refunds ("Cash", "Fund",
 * or an unknown value).
 */
{ code: "TransferTypeRejected" } | 
/**
 * REF-070 — bank_account_id was provided as empty.
 */
{ code: "BankAccountRequired" } | 
/**
 * REF-070 — bank_account_id was provided but the account does not exist.
 */
{ code: "BankAccountNotFound"; id: string } | 
/**
 * The source procedure has no associated fund — cannot create the refund
 * FundPaymentGroup.
 */
{ code: "SourceHasNoFund"; id: string } | 
/**
 * REF-240 — the fund payment group belongs to an overpayment refund and
 * must be removed via cancel, not direct deletion.
 */
{ code: "RefundGroupProtected" } | 
/**
 * Cancel path (REF-210) — no overpayment record was found for the given
 * source_procedure_id.
 */
{ code: "RefundRecordNotFound" } | 
/**
 * Failure from a repository or service the orchestrator delegates to.
 * Logged at the call site; the wire surface carries no detail.
 */
{ code: "DatabaseError" }
/**
 * Parsed Excel file with metadata (total record count)
 */
export type ParseExcelResponse = { patients: ExcelPatient[]; funds: ExcelFund[]; procedures: ExcelProcedure[]; total_records: number; parsing_issues: ParsingIssues }
/**
 * Parsing issues encountered during Excel file parsing
 */
export type ParsingIssues = { skipped_rows: SkippedRow[]; missing_sheets: string[] }
/**
 * Patient aggregate root
 */
export type Patient = { id: string; is_anonymous: boolean; name: string | null; ssn: string | null; 
/**
 * Temporary ID used during batch imports to map temp_id → real_id
 * None for patients created through regular API
 * Some(uuid) for patients created via Excel import
 */
temp_id?: string | null; 
/**
 * Tracking fields for procedure defaults
 * Updated when new procedures are created, used to pre-populate procedure form
 */
latest_procedure_type: string | null; latest_fund: string | null; latest_date: string; latest_procedure_amount: number | null }
/**
 * Patient candidate for batch import - semantically different from Patient (lacks ID, created_at)
 */
export type PatientCandidate = { temp_id: string; name: string | null; ssn: string | null }
/**
 * Errors raised by the Patient bounded context.
 * 
 * Wire shape: each variant serializes as `{ "code": "<VariantName>", ... }`
 * (struct fields when present). The frontend narrows on `code` per F27.
 */
export type PatientError = 
/**
 * Non-anonymous patient was constructed with an empty (or whitespace-only) name.
 */
{ code: "NameEmpty" } | 
/**
 * Non-anonymous patient was constructed without a name field.
 */
{ code: "NonAnonymousRequiresName" } | 
/**
 * SSN payload does not match the 13-ASCII-digit format. The SSN value is
 * intentionally NOT carried as a payload — see § Logging hygiene in
 * CLAUDE.md (PII must not appear on the wire).
 */
{ code: "InvalidSsn" } | 
/**
 * Infra failure from the repository / sqlx layer. The underlying error
 * is logged via `tracing::error!` at the call site; the wire surface
 * carries no detail to avoid leaking implementation specifics.
 */
{ code: "DatabaseError" }
/**
 * Validation result wraps candidate with validation outcome
 */
export type PatientValidationResult = { candidate: PatientCandidate; status: PatientValidationStatus; existing_id: string | null; error: string | null }
/**
 * Validation status for patient candidate
 */
export type PatientValidationStatus = "VALID" | "ALREADY_EXISTS" | "INVALID"
/**
 * Payment method for a healthcare procedure
 * 
 * Represents how a procedure payment was made, inferred from Excel import data:
 * - None: No payment information or no confirmed payment date (default)
 * - Cash: Electronic payment (ES code in Excel)
 * - Check: Check payment (CH code in Excel)
 * - BankCard: Credit/debit card payment (not currently in Excel imports, handled later)
 * - BankTransfer: Bank transfer (inferred when confirmed_payment_date exists but no explicit method)
 */
export type PaymentMethod = "NONE" | "CASH" | "CHECK" | "BANK_CARD" | "BANK_TRANSFER"
/**
 * Complete parse result for a PDF statement
 */
export type PdfParseResult = { 
/**
 * All procedure groups found in the document
 */
groups: PdfProcedureGroup[]; 
/**
 * Number of lines that could not be parsed
 */
unparsed_line_count: number; 
/**
 * Sample unparsed lines for debugging (max 5)
 */
unparsed_lines: string[] }
/**
 * A group of procedure lines paid by the same fund on the same date
 */
export type PdfProcedureGroup = { 
/**
 * Fund short label from data lines (e.g., "CPAM n° 931")
 */
fund_label: string; 
/**
 * Full fund description from the total line
 */
fund_full_name: string; 
/**
 * Payment date for this group
 */
payment_date: string; 
/**
 * Total amount stated in the PDF (thousandths of a euro)
 */
total_amount: number; 
/**
 * Whether the sum of line amounts matches the stated total
 */
is_total_valid: boolean; 
/**
 * Individual procedure lines in this group
 */
lines: NormalizedPdfLine[] }
/**
 * Healthcare Procedure aggregate root
 * 
 * Represents a healthcare procedure (service/procedure) record with foreign key references
 * to Patient, Fund, and Procedure Type. Uses soft-delete pattern.
 * 
 * Payment tracking:
 * - billed_amount: Total amount charged/invoiced for the procedure (thousandths of a euro)
 * - paid_amount: Amount actually paid/received from patient or fund (thousandths of a euro)
 * - confirmed_payment_date: When the payment was confirmed (from reconciliation)
 * - payment_method: How payment was made (Cash/Check/BankCard/BankTransfer/None)
 */
export type Procedure = { 
/**
 * Foreign key to Patient (required)
 */
patient_id: string; 
/**
 * Foreign key to Fund (optional - procedure can exist without a fund)
 */
fund_id: string | null; 
/**
 * Foreign key to ProcedureType (required)
 */
procedure_type_id: string; 
/**
 * Procedure date (required, ISO format: YYYY-MM-DD)
 */
procedure_date: string; 
/**
 * Total amount charged/invoiced for this procedure, in thousandths of a euro (e.g. 1234 = 1.234 €).
 * Mandatory: PRO-120 requires a non-null value at the domain level. When no value is
 * propagated from the patient's history (PRO-020) or the procedure type's
 * `default_amount` (PRO-025), the form submits `0`.
 * Source: Excel import column F or manual entry.
 */
billed_amount: number; 
/**
 * Payment method used for this procedure
 * Determines how payment was made: Cash/Check/BankCard/BankTransfer/None
 * - Cash: Electronic payment (ES in Excel)
 * - Check: Check payment (CH in Excel)
 * - BankCard: Credit/debit card (available for future use)
 * - BankTransfer: Inferred from confirmed_payment_date during reconciliation
 * - None: No payment information or no confirmed payment date
 */
payment_method: PaymentMethod; 
/**
 * Procedure status in the reconciliation lifecycle
 * Tracks progress through: None → Created → Reconciled → FundPaid (or DirectlyPaid)
 * - None: Initial state
 * - Created: Procedure created, awaiting reconciliation
 * - Reconciled: Associated with a fund payment group
 * - DirectlyPaid: Paid directly (cash/card), no fund reconciliation
 * - FundPaid: Bank payment matched via fund reconciliation
 */
payment_status: ProcedureStatus; 
/**
 * Stage 1 — fund-declared payment date from the fund document
 * (ISO format: YYYY-MM-DD). Set by fund-payment-* reconciliation
 * flows when the procedure enters a `FundPaymentGroup` (PRO-250,
 * FPM-320, FPA-300); cleared on removal (FPM-310, FPM-400).
 * Distinct from `confirmed_payment_date` which is Stage 2 only.
 */
fund_reconciliation_date: string; 
/**
 * Stage 2 — bank-side confirmed payment date (ISO format:
 * YYYY-MM-DD). Set by bank-statement-* reconciliation flows when
 * the procedure's group is matched to a bank transfer, or
 * directly at Excel import (column J) for procedures arriving
 * with payment data already present.
 * Presence of this date triggers BankTransfer inference if
 * payment_method not explicit.
 */
confirmed_payment_date: string; 
/**
 * Actual amount paid/received from patient or fund, in thousandths of a euro (e.g. 1234 = 1.234 €)
 * May differ from billed_amount (partial payment, overpayment, etc.)
 * Source: Excel import column K or reconciliation statement
 */
paid_amount: number | null; 
/**
 * Metadata - not a domain property
 */
id: string }
/**
 * Candidate procedure for batch creation and validation for orchestrators
 */
export type ProcedureCandidate = { patient_id: string; fund_id: string | null; procedure_type_id: string; procedure_date: string; billed_amount: number; payment_method: string | null; confirmed_payment_date: string | null; paid_amount: number | null; awaited_amount: number | null }
/**
 * Errors raised by the Procedure bounded context.
 * 
 * Wire shape: each variant serializes as `{ "code": "<VariantName>", ... }`
 * (struct fields when present). The frontend narrows on `code` per F27.
 * 
 * Scope note (PR 1 of typed-error migration): the variants listed here cover
 * every error path the BC's domain + service layer can currently produce.
 * The `Procedure` aggregate's CRUD commands are not wired through this BC's
 * api.rs (they live in `use_cases/procedure_orchestration/api.rs` and become
 * wire-typed in PR 3 of the migration). The corresponding variants
 * (`PatientIdEmpty`, `ProcedureTypeIdEmpty`, `Refund*`) are reachable through
 * `Procedure::new` / `ProcedureRefund::new`, called from those use cases.
 */
export type ProcedureError = 
/**
 * `Procedure::validate` rejected an empty patient ID.
 */
{ code: "PatientIdEmpty" } | 
/**
 * `Procedure::validate` rejected an empty procedure type ID.
 */
{ code: "ProcedureTypeIdEmpty" } | 
/**
 * A `Procedure` lookup by id returned no row (e.g. the delete guard in
 * `ProcedureOrchestrationService` reading the target before deletion).
 */
{ code: "ProcedureNotFound"; procedure_id: string } | 
/**
 * `ProcedureType::validate_fields` rejected an empty/whitespace name.
 */
{ code: "ProcedureTypeNameEmpty" } | 
/**
 * `ProcedureType::validate_fields` rejected a negative default amount.
 */
{ code: "DefaultAmountNegative" } | 
/**
 * `ProcedureTypeService` lookup by id returned no row.
 */
{ code: "ProcedureTypeNotFound"; procedure_type_id: string } | 
/**
 * `ProcedureTypeService` add/update rejected because another row already
 * uses the same name.
 */
{ code: "ProcedureTypeNameDuplicate" } | 
/**
 * `ProcedureTypeService` rejected mutation of the reserved `import-pdf`
 * procedure type.
 */
{ code: "ReservedTypeNotMutable" } | 
/**
 * `ProcedureRefund::validate` rejected a reason exceeding the 255-char cap.
 */
{ code: "RefundReasonTooLong" } | 
/**
 * `ProcedureRefund::new` rejected a refund date that does not parse as
 * `YYYY-MM-DD`.
 */
{ code: "InvalidRefundDateFormat" } | 
/**
 * Repository / sqlx-level failure. Underlying error is logged at the
 * call site via `tracing::error!`; the wire surface carries no detail.
 */
{ code: "DatabaseError" }
/**
 * Composite error for the procedure-orchestration use case.
 * 
 * Holds ONLY `#[from]` wrappers — the Procedure BC enum and the use-case task
 * sub-enum. Both carry their own `#[serde(tag = "code")]`, so the untagged
 * composite flattens to a single `{ "code": "...", ... }` payload on the wire.
 * 
 * Both arms emit `{ "code": "DatabaseError" }`; collision intentional — see
 * `docs/techdebt.md`.
 */
export type ProcedureOrchestrationError = ProcedureError | ProcedureOrchestrationTask
/**
 * Use-case-specific guards and catch-alls for procedure orchestration.
 * 
 * These are codes that do NOT belong to the Procedure bounded context: the
 * orchestrator validates cross-context foreign keys (patient, fund), enforces
 * a delete guard, parses the wire `procedure_date`, and translates failures
 * from the patient / fund / procedure-type / refund repositories it holds
 * directly. Tagged with `code` so each variant emits `{ "code": "..." }`.
 */
export type ProcedureOrchestrationTask = 
/**
 * FK validation: the referenced patient does not exist (or is deleted).
 */
{ code: "PatientNotFound"; patient_id: string } | 
/**
 * FK validation: the referenced fund does not exist (or is deleted).
 */
{ code: "FundNotFound"; fund_id: string } | 
/**
 * Delete guard: the procedure is linked to a fund payment group or bank
 * transaction (a blocking status) and cannot be deleted directly.
 */
{ code: "ProcedureDeleteBlocked" } | 
/**
 * The wire `procedure_date` did not parse as `YYYY-MM-DD`.
 */
{ code: "InvalidProcedureDate" } | 
/**
 * Failure from a repository the orchestrator holds directly (patient /
 * fund / procedure-type / refund). Logged at the call site via
 * `tracing::error!`; the wire surface carries no detail.
 */
{ code: "DatabaseError" }
/**
 * DTO for surfacing ProcedureRefund data to the frontend.
 * Used when the OverpaymentRefund modal needs to resolve source_procedure_id (REF-200).
 */
export type ProcedureRefundInfo = { id: string; source_procedure_id: string; refund_procedure_id: string; refund_date: string; reason: string | null; previous_payment_status: ProcedureStatus }
/**
 * Procedure status lifecycle
 * 
 * Represents the reconciliation state of a healthcare procedure:
 * - None: Initial state, no reconciliation activity
 * - Created: Procedure has been created and is awaiting payment/reconciliation
 * - Reconciled: A fund payment group has been associated with this procedure
 * - DirectlyPaid: Procedure was paid directly (cash/card) without fund reconciliation (blocking re-import)
 * - FundPaid: A bank payment has been matched/reconciled with this procedure via fund (blocking re-import)
 * - ImportDirectlyPaid: From Excel import — paid directly (ES/CH), non-blocking re-import
 * - ImportFundPaid: From Excel import — fund present, method not ES/CH (non-blocking re-import)
 * - Overpaid: Source procedure whose full overpayment has been recorded (REF-160). Blocks deletion (REF-220).
 * - OverpaymentRefund: Mirror negative procedure created to offset an overpayment (REF-090). Blocks deletion (REF-230).
 */
export type ProcedureStatus = "NONE" | "CREATED" | "RECONCILED" | 
/**
 * Fund reconciliation done but amount disputed: paid_amount ≠ billed_amount
 */
"PARTIALLY_RECONCILED" | "DIRECTLY_PAID" | "FUND_PAID" | 
/**
 * Bank transfer confirmed for a partially reconciled procedure
 */
"PARTIALLY_FUND_PAID" | "IMPORT_DIRECTLY_PAID" | "IMPORT_FUND_PAID" | 
/**
 * Source procedure whose full overpayment has been recorded (REF-160)
 */
"OVERPAID" | 
/**
 * Mirror negative procedure created to offset an overpayment (REF-090)
 */
"OVERPAYMENT_REFUND"
/**
 * Procedure Type aggregate root
 * 
 * Represents a type of healthcare service or procedure with a standard name and default amount.
 * Used to categorize procedures and provide default financial amounts.
 */
export type ProcedureType = { name: string; default_amount: number; category: string | null; 
/**
 * Metadata - not a domain property
 */
id: string }
/**
 * Result of validating a procedure candidate
 */
export type ProcedureValidationResult = { candidate: ProcedureCandidate; status: ProcedureValidationStatus; error: string | null }
/**
 * Validation status for a procedure candidate
 */
export type ProcedureValidationStatus = "VALID" | "INVALID"
/**
 * Raw healthcare procedure data from frontend (unvalidated)
 * Used for updating an existing procedure with data from an external source
 */
export type RawProcedure = { id: string; patient_id: string; fund_id: string | null; procedure_type_id: string; procedure_date: string; billed_amount: number; payment_method: string | null; fund_reconciliation_date: string | null; confirmed_payment_date: string | null; paid_amount: number | null; payment_status: string }
/**
 * Raw procedure type data from frontend (unvalidated)
 */
export type RawProcedureType = { id: string; name: string; default_amount: number; category: string | null }
/**
 * Response from PDF reconciliation workflow
 */
export type ReconcileAndCandidatesResponse = { 
/**
 * Grouped payment candidates ready for user validation
 */
candidates: FundPaymentGroupCandidate[]; 
/**
 * Raw reconciliation details for reference
 */
reconciliation: ReconciliationResult; 
/**
 * `true` when every candidate maps to an existing `FundPaymentGroup`
 * (same `fund_label` + `payment_date` + `total_amount`). The frontend
 * renders an "already imported" empty-state instead of the anomaly UI
 * and refuses to dispatch downstream commands — guarding against the
 * silent partial mutation that would otherwise occur if the user
 * reached the auto-correction step.
 */
already_imported: boolean }
/**
 * A reconciliation match result (unified discriminated union for all scenarios)
 */
export type ReconciliationMatch = 
/**
 * PDF line matched perfectly to one DB procedure (no anomalies)
 */
{ type: "PerfectSingleMatch"; data: { pdf_line: NormalizedPdfLine; db_match: DbMatch } } | 
/**
 * PDF line matched perfectly to multiple DB procedures (no anomalies)
 */
{ type: "PerfectGroupMatch"; data: { pdf_line: NormalizedPdfLine; db_matches: DbMatch[] } } | 
/**
 * PDF line matched to one DB procedure with anomalies
 */
{ type: "SingleMatchIssue"; data: { pdf_line: NormalizedPdfLine; db_match: DbMatch } } | 
/**
 * PDF line matched to multiple DB procedures with anomalies
 */
{ type: "GroupMatchIssue"; data: { pdf_line: NormalizedPdfLine; db_matches: DbMatch[] } } | 
/**
 * Too many procedures found for a single PDF line (above threshold, unresolvable)
 */
{ type: "TooManyMatchIssue"; data: { pdf_line: NormalizedPdfLine; candidate_ids: string[] } } | 
/**
 * PDF line not found in database; nearby_candidates are unreconciled procedures within ±1 day
 */
{ type: "NotFoundIssue"; data: { pdf_line: NormalizedPdfLine; nearby_candidates: NotFoundCandidate[] } }
/**
 * Complete reconciliation result structured as unified matches
 */
export type ReconciliationResult = { 
/**
 * Unified array of all reconciliation matches (perfect + issues)
 */
matches: ReconciliationMatch[] }
/**
 * Payload assembled by the frontend when the practitioner clicks Report.
 * 
 * All strings are pre-resolved: labels are already translated, dates are
 * already formatted, currency values are already grouped and suffixed.
 * The renderer only places strings; it never inspects content (FPR-013, FPR-021).
 */
export type ReportGenerationRequest = { 
/**
 * Bold heading shown at the top of page 1 (FPR-020).
 */
title: string; 
/**
 * Breadcrumb shown at the top of pages 2+, e.g. "Reconciliation Report (continued)".
 */
continuation_title: string; 
/**
 * Lines rendered below the title on page 1 (period, generated-on, source-PDF, etc.).
 * The frontend produces complete pre-formatted strings; the renderer prints them in order.
 */
header_lines: string[]; 
/**
 * Section 1 — unreconciled procedures (FPR-030 to FPR-033).
 */
unreconciled: UnreconciledSection; 
/**
 * Heading for Section 2. Rendered only when `correction_groups` is non-empty.
 */
correction_section_heading: string; 
/**
 * Section 2 — corrections grouped by type (FPR-040 to FPR-042).
 * An empty list omits the entire section (FPR-040).
 */
correction_groups: CorrectionGroup[]; 
/**
 * Footer page-number label, e.g. "Page" — rendered as `"{label} {n} / {total}"` (FPR-022).
 */
page_label: string }
/**
 * Errors produced by the `generate_fund_reconciliation_report_pdf` and
 * `export_and_open_fund_reconciliation_report_pdf` commands. This is the
 * FE-facing wire type — each variant serializes as `{ "code": "<Variant>" }`.
 * 
 * The `detail` strings are diagnostic context (which field failed validation,
 * which font/IO operation broke). They stay server-side for `Display` +
 * `tracing` and the validator's unit tests; `#[serde(skip)]` keeps them off the
 * wire, where they would leak infra detail with no FE value.
 */
export type ReportPdfError = 
/**
 * The `ReportGenerationRequest` payload is structurally invalid.
 * 
 * Triggered when: a required pre-resolved string is empty, exceeds the
 * length cap, contains control characters, or a collection (header
 * lines, unreconciled rows, correction groups, correction rows) exceeds
 * its DoS-guard cap. See `request::validate_safe_string`.
 */
{ code: "InvalidRequest" } | 
/**
 * PDF rendering failed after validation passed — e.g. font load error,
 * internal printpdf error, or I/O error.
 */
{ code: "PdfGenerationFailed" } | 
/**
 * Writing the rendered PDF bytes to the destination failed (permission
 * denied, disk full, missing parent directory, etc.).
 */
{ code: "WriteFailed" } | 
/**
 * Launching the system default application for the saved file failed
 * (no associated app, platform launcher refused, etc.). The file has
 * already been written when this error is returned.
 */
{ code: "OpenFailed" }
/**
 * A credit line that has been resolved with a fund ID
 */
export type ResolvedCreditLine = { date: string; label: string; amount: number; fund_id: string }
/**
 * Request to save or update a single amount → procedure type mapping
 */
export type SaveExcelAmountMappingRequest = { amount: number; procedure_type_id: string }
/**
 * Request to save label mappings
 */
export type SaveLabelMappingRequest = { bank_label: string; fund_id: string }
/**
 * Information about a skipped row during parsing
 */
export type SkippedRow = { sheet: string; row_number: number; reason: string }
/**
 * Column-header strings for the unreconciled table (FPR-031). Fixed 4 columns.
 */
export type UnreconciledColumns = { date: string; patient: string; ssn: string; amount: string }
/**
 * An unreconciled procedure for the post-reconciliation report
 */
export type UnreconciledProcedure = { procedure_id: string; patient_name: string; ssn: string; procedure_date: string; amount: number }
/**
 * One row of the unreconciled table (FPR-031). All four cells are pre-formatted.
 */
export type UnreconciledRow = { date: string; patient: string; ssn: string; amount: string }
/**
 * Section 1 content. Either an empty-state confirmation, or a table with rows + total.
 */
export type UnreconciledSection = 
/**
 * FPR-032 — empty-state branch. No table, no total.
 */
{ type: "Empty"; data: { heading: string; empty_message: string } } | 
/**
 * FPR-031, FPR-033 — populated table with header row, data rows, and total.
 */
{ type: "Rows"; data: { heading: string; column_headers: UnreconciledColumns; rows: UnreconciledRow[]; total_label: string; total_value: string } }
/**
 * Complex response: validation results
 */
export type ValidateBatchFundsResponse = { results: FundValidationResult[] }
/**
 * Complex response: validation results
 */
export type ValidateBatchPatientsResponse = { results: PatientValidationResult[] }
/**
 * Response DTO for procedure batch validation
 */
export type ValidateBatchProceduresResponse = { results: ProcedureValidationResult[] }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
