// @ts-nocheck
/* eslint-disable */
// Generated by Specta - do not edit manually

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Tauri command: Add a new patient
 */
async addPatient(name: string | null, ssn: string | null) : Promise<Result<Patient, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_patient", { name, ssn }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Read all patients
 */
async readAllPatients() : Promise<Result<Patient[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_all_patients") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Update an existing patient
 */
async updatePatient(patient: Patient) : Promise<Result<Patient, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_patient", { patient }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Delete a patient
 */
async deletePatient(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_patient", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Validate batch of patient candidates
 */
async validateBatchPatients(patients: PatientCandidate[]) : Promise<Result<ValidateBatchPatientsResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_batch_patients", { patients }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Create batch of patients
 */
async createBatchPatients(patients: PatientCandidate[]) : Promise<Result<CreateBatchPatientsResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_batch_patients", { patients }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Add a new affiliated fund
 */
async addFund(fundIdentifier: string, fundName: string) : Promise<Result<AffiliatedFund, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_fund", { fundIdentifier, fundName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Read all affiliated funds
 */
async readAllFunds() : Promise<Result<AffiliatedFund[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_all_funds") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Update an existing affiliated fund
 */
async updateFund(fund: AffiliatedFund) : Promise<Result<AffiliatedFund, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_fund", { fund }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Delete an affiliated fund
 */
async deleteFund(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_fund", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Validate batch of fund candidates
 */
async validateBatchFunds(funds: FundCandidate[]) : Promise<Result<ValidateBatchFundsResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_batch_funds", { funds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Create batch of funds
 */
async createBatchFunds(funds: FundCandidate[]) : Promise<Result<CreateBatchFundsResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_batch_funds", { funds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Add a new healthcare procedure
 */
async addProcedure(patientId: string, fundId: string | null, procedureTypeId: string, procedureDate: string, procedureAmount: number | null) : Promise<Result<Procedure, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_procedure", { patientId, fundId, procedureTypeId, procedureDate, procedureAmount }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Read all procedures
 */
async readAllProcedures() : Promise<Result<Procedure[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_all_procedures") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Update an existing procedure
 */
async updateProcedure(raw: RawProcedure) : Promise<Result<Procedure, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_procedure", { raw }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Delete a procedure
 */
async deleteProcedure(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_procedure", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Validate batch of procedure candidates
 */
async validateBatchProcedures(procedures: ProcedureCandidate[]) : Promise<Result<ValidateBatchProceduresResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_batch_procedures", { procedures }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Create batch of procedures
 */
async createBatchProcedures(procedures: ProcedureCandidate[]) : Promise<Result<CreateBatchProceduresResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_batch_procedures", { procedures }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Get unpaid procedures by fund
 */
async getUnpaidProceduresByFund(fundId: string) : Promise<Result<Procedure[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_unpaid_procedures_by_fund", { fundId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Get procedures by their IDs
 */
async readProceduresByIds(ids: string[]) : Promise<Result<Procedure[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_procedures_by_ids", { ids }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Add a new procedure type
 */
async addProcedureType(name: string, defaultAmount: number, category: string | null) : Promise<Result<ProcedureType, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_procedure_type", { name, defaultAmount, category }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Read all procedure types
 */
async readAllProcedureTypes() : Promise<Result<ProcedureType[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_all_procedure_types") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Update an existing procedure type
 */
async updateProcedureType(raw: RawProcedureType) : Promise<Result<ProcedureType, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_procedure_type", { raw }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Delete a procedure type
 */
async deleteProcedureType(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_procedure_type", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Parse Excel file (preview step — no DB writes)
 */
async parseExcelFile(filePath: string) : Promise<Result<ParseExcelResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("parse_excel_file", { filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Execute Excel import (creates patients, funds, and procedures)
 * 
 * `parsed_data` must be the exact response from `parse_excel_file` — do NOT re-parse,
 * because `procedure_type_tmp_id` UUIDs are generated randomly and must match the mapping.
 * 
 * `procedure_type_mapping` maps `procedure_type_tmp_id → procedure_type_id` as selected
 * by the user in the type-mapping UI step.
 */
async executeExcelImport(parsedData: ParseExcelResponse, procedureTypeMapping: Partial<{ [key in string]: string }>, selectedMonths: string[]) : Promise<Result<ImportExecutionResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("execute_excel_import", { parsedData, procedureTypeMapping, selectedMonths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Return all saved Excel amount → procedure type mappings
 */
async getExcelAmountMappings() : Promise<Result<ExcelAmountMapping[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_excel_amount_mappings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Save (upsert) Excel amount → procedure type mappings
 */
async saveExcelAmountMappings(mappings: SaveExcelAmountMappingRequest[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_excel_amount_mappings", { mappings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Handler for PDF text extraction from file path
 */
async extractPdfText(filePath: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("extract_pdf_text", { filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Handler for PDF text extraction from bytes
 */
async extractPdfTextFromBytes(bytes: number[]) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("extract_pdf_text_from_bytes", { bytes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Handler for parsing extracted PDF text into structured procedure groups.
 * Normalization (French date parsing) happens here — lines with unparseable
 * dates are counted as unparsed rather than propagating errors.
 */
async parsePdfText(text: string) : Promise<Result<PdfParseResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("parse_pdf_text", { text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Handler for reconciling PDF procedures with database
 */
async reconcilePdfProcedures(parseResult: PdfParseResult) : Promise<Result<ReconciliationResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reconcile_pdf_procedures", { parseResult }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Handler for complete reconciliation workflow: reconcile PDF and group into candidates
 */
async reconcileAndCreateCandidates(parseResult: PdfParseResult) : Promise<Result<ReconcileAndCandidatesResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reconcile_and_create_candidates", { parseResult }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Handler for exporting reconciliation results to CSV format
 */
async exportReconciliationCsv(result: ReconciliationResult) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_reconciliation_csv", { result }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Handler for creating fund payment groups from validated reconciliation candidates
 */
async createFundPaymentFromCandidates(request: CreateFundPaymentFromCandidatesRequest) : Promise<Result<FundPaymentGroup[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_fund_payment_from_candidates", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Handler for creating fund payment groups with auto-corrections for anomalies
 */
async createFundPaymentWithAutoCorrections(request: CreateFundPaymentWithAutoCorrectionsRequest) : Promise<Result<FundPaymentGroup[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_fund_payment_with_auto_corrections", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Handler for getting all unreconciled procedures in a date range (for post-reconciliation report)
 */
async getUnreconciledProceduresInRange(startDate: string, endDate: string) : Promise<Result<UnreconciledProcedure[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_unreconciled_procedures_in_range", { startDate, endDate }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Read all fund payment groups
 * 
 * Computes is_locked for each group by checking if any associated procedure
 * is in a bank-reconciled status (FundPayed or PartiallyFundPayed).
 */
async readAllFundPaymentGroups() : Promise<Result<FundPaymentGroup[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_all_fund_payment_groups") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Delete a fund payment group with procedure cleanup
 * 
 * Deletes the group, its lines, and resets associated procedures
 * (status → Created, clears confirmed_payment_date and actual_payment_amount)
 */
async deleteFundPaymentGroup(groupId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_fund_payment_group", { groupId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Create a fund payment group from manual UI selection
 * 
 * Calculates total_amount from procedure amounts and sets procedures to Reconciliated.
 */
async createFundPaymentGroup(fundId: string, paymentDate: string, procedureIds: string[]) : Promise<Result<FundPaymentGroup, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_fund_payment_group", { fundId, paymentDate, procedureIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Update a fund payment group with new procedures
 * 
 * Handles add/remove procedure logic via orchestrator:
 * - Removed procedures → reset to Created
 * - Added procedures → set to Reconciliated
 * - Recalculates total_amount
 * - Rejects if any procedure is bank-reconciled (FundPayed/PartiallyFundPayed)
 */
async updateFundPaymentGroupWithProcedures(groupId: string, paymentDate: string, procedureIds: string[]) : Promise<Result<FundPaymentGroup, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_fund_payment_group_with_procedures", { groupId, paymentDate, procedureIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Get edit data for a fund payment group
 * 
 * Returns two classified lists server-side so the frontend only handles display:
 * - `current_procedures`: in the group (Reconciliated / PartiallyReconciled)
 * - `available_procedures`: Created procedures for the same fund, not in the group
 */
async getFundPaymentGroupEditData(groupId: string, fundId: string) : Promise<Result<FundPaymentGroupEditData, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_fund_payment_group_edit_data", { groupId, fundId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Create a new bank transfer
 */
async createBankTransfer(transferDate: string, amount: number, transferType: BankTransferType, bankAccountId: string, source: string) : Promise<Result<BankTransfer, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_bank_transfer", { transferDate, amount, transferType, bankAccountId, source }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Read all bank transfers with account info
 */
async readAllBankTransfers() : Promise<Result<BankTransfer[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_all_bank_transfers") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Read a single bank transfer with account info
 */
async readBankTransfer(id: string) : Promise<Result<BankTransfer | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_bank_transfer", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Update an existing bank transfer
 */
async updateBankTransfer(transfer: BankTransfer) : Promise<Result<BankTransfer, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_bank_transfer", { transfer }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Delete a bank transfer
 */
async deleteBankTransfer(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_bank_transfer", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Create a new bank account
 */
async createBankAccount(name: string, iban: string | null) : Promise<Result<BankAccount, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_bank_account", { name, iban }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Read all bank accounts
 */
async readAllBankAccounts() : Promise<Result<BankAccount[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_all_bank_accounts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Read a single bank account
 */
async readBankAccount(id: string) : Promise<Result<BankAccount | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_bank_account", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Update a bank account
 */
async updateBankAccount(id: string, name: string, iban: string | null) : Promise<Result<BankAccount, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_bank_account", { id, name, iban }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: Delete a bank account
 */
async deleteBankAccount(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_bank_account", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Parse a bank statement PDF and return structured data
 */
async parseBankStatement(bytes: number[]) : Promise<Result<BankStatementParseResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("parse_bank_statement", { bytes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resolve a bank account from IBAN
 */
async resolveBankAccountFromIban(iban: string) : Promise<Result<BankAccount | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_bank_account_from_iban", { iban }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resolve fund labels for a bank account
 */
async resolveBankFundLabels(bankAccountId: string, labels: string[]) : Promise<Result<FundLabelResolution[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_bank_fund_labels", { bankAccountId, labels }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save confirmed fund label mappings
 */
async saveBankFundLabelMappings(bankAccountId: string, mappings: SaveLabelMappingRequest[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_bank_fund_label_mappings", { bankAccountId, mappings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Match resolved credit lines against unsettled fund payment groups
 */
async matchBankStatementLines(resolvedLines: ResolvedCreditLine[]) : Promise<Result<BankStatementMatchResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("match_bank_statement_lines", { resolvedLines }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create bank transfers from confirmed matches
 */
async createBankTransfersFromStatement(bankAccountId: string, confirmedMatches: ConfirmedMatch[]) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_bank_transfers_from_statement", { bankAccountId, confirmedMatches }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get bank statement reconciliation configuration
 */
async getBankStatementReconciliationConfig() : Promise<BankStatementReconciliationConfig> {
    return await TAURI_INVOKE("get_bank_statement_reconciliation_config");
},
/**
 * Tauri command: Health check
 */
async checkHealth() : Promise<HealthResponse> {
    return await TAURI_INVOKE("check_health");
},
async logFrontend(level: string, message: string) : Promise<void> {
    await TAURI_INVOKE("log_frontend", { level, message });
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * AffiliatedFund aggregate root
 */
export type AffiliatedFund = { fund_identifier: string; name: string; 
/**
 * Temporary ID used during batch imports to map temp_id → real_id
 * None for funds created through regular API
 * Some(uuid) for funds created via Excel import
 */
temp_id?: string | null; 
/**
 * Metadata - not a domain property
 */
id: string }
/**
 * Type of detected anomaly
 */
export type AnomalyType = 
/**
 * Fund in PDF differs from fund in database
 */
"FundMismatch" | 
/**
 * Amount in PDF differs from amount in database
 */
"AmountMismatch" | 
/**
 * Procedure date is off by 1 day (matched via date-1 pass)
 */
"DateMismatch"
/**
 * Auto-correction action for an anomaly
 */
export type AutoCorrection = 
/**
 * Update procedure amount to PDF amount
 */
{ AmountMismatch: { procedure_id: string; pdf_amount: number } } | 
/**
 * Update procedure fund to PDF fund
 */
{ FundMismatch: { procedure_id: string; pdf_fund_label: string } } | 
/**
 * Update procedure date to PDF date
 */
{ DateMismatch: { procedure_id: string; pdf_date: string } } | 
/**
 * Create new procedure from PDF line (creates patient if not found)
 */
{ CreateProcedure: { ssn: string; patient_name: string; procedure_date: string; payment_date: string; procedure_amount: number; pdf_fund_label: string } } | 
/**
 * Link existing procedure to fund payment and correct patient SSN from PDF
 */
{ LinkProcedure: { procedure_id: string; pdf_ssn: string; pdf_fund_label: string; payment_date: string } } | 
/**
 * Contest the fund payment amount: keep procedure_amount unchanged,
 * set actual_payment_amount to the PDF amount (what the fund claims to have paid).
 * Sets payment_status to PartiallyReconciled.
 */
{ ContestAmount: { procedure_id: string; 
/**
 * Amount actually paid by the fund (from PDF), in millièmes
 */
actual_payment_amount: number } }
/**
 * Bank Account aggregate root
 * Represents a bank account used for transfers
 */
export type BankAccount = { name: string; iban: string | null; 
/**
 * Metadata - not a domain property
 */
id: string }
/**
 * A mapping between a bank label (as seen on statements) and a fund
 */
export type BankFundLabelMapping = { id: string; bank_account_id: string; bank_label: string; fund_id: string | null }
/**
 * A single credit line from a bank statement (VIR SEPA only)
 */
export type BankStatementCreditLine = { 
/**
 * ISO date YYYY-MM-DD
 */
date: string; 
/**
 * Fund label extracted from VIR SEPA, e.g. "CPAM93", "MUTUELLEGENERALEEDUCATIONNAT"
 */
label: string; 
/**
 * Credit amount in millièmes (1€ = 1000)
 */
amount: number }
/**
 * A match between a bank statement credit line and a FundPaymentGroup
 */
export type BankStatementMatch = { credit_line: ResolvedCreditLine; group_id: string; group_fund_id: string; group_payment_date: string; group_total_amount: number }
/**
 * Result of matching bank statement lines against unsettled groups
 */
export type BankStatementMatchResult = { matched: BankStatementMatch[]; unmatched_lines: ResolvedCreditLine[] }
/**
 * Result of parsing a bank statement PDF
 */
export type BankStatementParseResult = { 
/**
 * IBAN extracted from PDF header (normalized, no spaces)
 */
iban: string | null; 
/**
 * Statement period, e.g. "du 01/05/2025 au 30/05/2025"
 */
period: string | null; 
/**
 * Credit lines from VIR SEPA entries
 */
credit_lines: BankStatementCreditLine[]; 
/**
 * Sum of all credit amounts in millièmes
 */
total_credits: number; 
/**
 * Number of lines that couldn't be parsed
 */
unparsed_count: number }
/**
 * Bank statement reconciliation configuration exported to frontend
 */
export type BankStatementReconciliationConfig = { 
/**
 * Maximum date offset (days) for matching bank lines to payment groups
 */
max_date_offset_days: number }
/**
 * BankTransfer aggregate root
 * Represents a payment transaction that will later be reconciled with procedures/funds
 */
export type BankTransfer = { id: string; transfer_date: string; amount: number; transfer_type: BankTransferType; bank_account: BankAccount; source: string }
/**
 * Payment type for bank transfers
 */
export type BankTransferType = "FUND" | "CHECK" | "CREDIT_CARD"
/**
 * A confirmed match ready for bank transfer creation
 */
export type ConfirmedMatch = { group_id: string; date: string; amount: number }
/**
 * Complex response: created funds + temp ID mapping for import tracking
 */
export type CreateBatchFundsResponse = { funds: AffiliatedFund[]; temp_id_map: Partial<{ [key in string]: string }> }
/**
 * Complex response: created patients + temp ID mapping for import tracking
 */
export type CreateBatchPatientsResponse = { patients: Patient[]; temp_id_map: Partial<{ [key in string]: string }> }
/**
 * Response DTO for procedure batch creation
 */
export type CreateBatchProceduresResponse = { procedures: Procedure[] }
/**
 * Request to create fund payment groups from validated candidates
 */
export type CreateFundPaymentFromCandidatesRequest = { 
/**
 * Validated candidates to process
 */
candidates: FundPaymentGroupCandidate[] }
/**
 * Request to create fund payment groups with auto-corrections
 */
export type CreateFundPaymentWithAutoCorrectionsRequest = { 
/**
 * Validated candidates to process
 */
candidates: FundPaymentGroupCandidate[]; 
/**
 * Auto-corrections to apply
 */
auto_corrections: AutoCorrection[] }
/**
 * A single DB procedure match within an issue
 */
export type DbMatch = { procedure_id: string; procedure_date: string; fund_id: string | null; amount: number | null; anomalies: AnomalyType[] }
/**
 * A saved mapping between a procedure amount (millièmes d'euro) and a procedure type id
 */
export type ExcelAmountMapping = { amount: number; procedure_type_id: string }
/**
 * Parsed fund data from Excel Secu sheet
 */
export type ExcelFund = { temp_id: string; fund_identifier: string; fund_name: string; fund_address: string | null }
/**
 * Parsed patient data from Excel Patiente sheet
 */
export type ExcelPatient = { temp_id: string; name: string; ssn: string; latest_fund: string | null }
/**
 * Parsed procedure data from Excel monthly sheets
 */
export type ExcelProcedure = { patient_temp_id: string; fund_temp_id: string | null; procedure_type_tmp_id: string; amount: number; procedure_date: string; sheet_month: string; payment_method: string | null; confirmed_payment_date: string | null; actual_payment_amount: number | null; awaited_amount: number | null }
/**
 * Fund candidate for batch import - semantically different from AffiliatedFund (lacks ID, created_at)
 */
export type FundCandidate = { temp_id: string; fund_identifier: string; fund_name: string }
/**
 * Resolution status for a bank statement fund label
 */
export type FundLabelResolution = { bank_label: string; 
/**
 * Fund ID if already confirmed via mapping table
 */
fund_id: string | null; 
/**
 * Suggested fund ID from heuristic matching
 */
suggested_fund_id: string | null; 
/**
 * Suggested fund name (for display)
 */
suggested_fund_name: string | null; 
/**
 * Whether this mapping is confirmed (from mapping table)
 */
is_confirmed: boolean; 
/**
 * Whether this label is explicitly rejected (not a fund payment)
 */
is_rejected: boolean }
/**
 * Validation result for a fund payment candidate
 */
export type FundPaymentCandidateValidation = { candidate: FundPaymentGroupCandidate; status: FundPaymentValidationStatus; error: string | null }
/**
 * FundPaymentGroup aggregate root
 * Represents a batch of payments from a single fund (e.g., CPAM payment run)
 */
export type FundPaymentGroup = { id: string; fund_id: string; payment_date: string; total_amount: number; lines: FundPaymentLine[]; 
/**
 * Computed at read time: true if any procedure in this group is bank-reconciled
 * (FundPayed or PartiallyFundPayed). Group cannot be edited or deleted when locked.
 */
is_locked?: boolean }
/**
 * Fund payment group candidate created from PDF reconciliation data
 * Groups matched procedures by (fund_id + payment_date)
 */
export type FundPaymentGroupCandidate = { 
/**
 * Fund identifier from PDF (e.g., "CPAM n° 931")
 */
fund_label: string; 
/**
 * Payment date (serialized as ISO string YYYY-MM-DD for frontend)
 */
payment_date: string; 
/**
 * Total amount stated in PDF for this group
 */
total_amount: number; 
/**
 * List of matched procedure IDs for this group
 */
procedure_ids: string[]; 
/**
 * Sum of matched procedure amounts
 */
matched_amount: number; 
/**
 * Coverage status: is matched_amount == total_amount?
 */
is_fully_covered: boolean }
/**
 * Response for the edit modal: procedures in the group + procedures available to add
 */
export type FundPaymentGroupEditData = { 
/**
 * Procedures currently in the group (Reconciliated / PartiallyReconciled)
 */
current_procedures: Procedure[]; 
/**
 * Created procedures for the same fund not yet in the group
 */
available_procedures: Procedure[] }
/**
 * FundPaymentLine aggregate
 * Links a fund payment group to a specific procedure
 */
export type FundPaymentLine = { id: string; fund_payment_group_id: string; procedure_id: string }
/**
 * Validation status for a fund payment candidate
 */
export type FundPaymentValidationStatus = "VALID" | "INVALID"
/**
 * Validation result wraps candidate with validation outcome
 */
export type FundValidationResult = { candidate: FundCandidate; status: FundValidationStatus; existing_id: string | null; error: string | null }
/**
 * Validation status for fund candidate
 */
export type FundValidationStatus = "VALID" | "ALREADY_EXISTS" | "INVALID"
export type HealthResponse = { status: string }
/**
 * Result of a completed Excel import execution
 */
export type ImportExecutionResult = { patients_created: number; patients_reused: number; funds_created: number; funds_reused: number; procedures_created: number; procedures_skipped: number; procedures_deleted: number; 
/**
 * Months (YYYY-MM) that were blocked because they contain reconciliated/fund-payed procedures.
 */
blocked_months: string[] }
/**
 * A normalized PDF procedure line — the ONE domain object for reconciliation.
 * 
 * All dates are NaiveDate (serialized as ISO YYYY-MM-DD via serde/specta).
 * Produced by the parser after normalization; used throughout the backend
 * and sent to the frontend via Tauri/Specta.
 */
export type NormalizedPdfLine = { 
/**
 * Unique index of the line in the original PDF
 */
line_index: number; 
/**
 * Payment date
 */
payment_date: string; 
/**
 * Invoice number
 */
invoice_number: string; 
/**
 * Fund/organism name (e.g., "CPAM n° 931")
 */
fund_name: string; 
/**
 * Patient name as registered with the fund
 */
patient_name: string; 
/**
 * Social security number (13 digits)
 */
ssn: string; 
/**
 * Nature of the act (e.g., "SF")
 */
nature: string; 
/**
 * Start date of the act or period
 */
procedure_start_date: string; 
/**
 * End date (same as start for single-date acts)
 */
procedure_end_date: string; 
/**
 * True if this line covers a period (start ≠ end)
 */
is_period: boolean; 
/**
 * Amount in millièmes (e.g. 1234 = 1.234 €)
 */
amount: number }
/**
 * A nearby unreconciled procedure candidate for manual linking
 */
export type NotFoundCandidate = { procedure_id: string; patient_name: string; ssn: string; procedure_date: string; amount: number }
/**
 * Parsed Excel file with metadata (total record count)
 */
export type ParseExcelResponse = { patients: ExcelPatient[]; funds: ExcelFund[]; procedures: ExcelProcedure[]; total_records: number; parsing_issues: ParsingIssues }
/**
 * Parsing issues encountered during Excel file parsing
 */
export type ParsingIssues = { skipped_rows: SkippedRow[]; missing_sheets: string[] }
/**
 * Patient aggregate root
 */
export type Patient = { id: string; is_anonymous: boolean; name: string | null; ssn: string | null; 
/**
 * Temporary ID used during batch imports to map temp_id → real_id
 * None for patients created through regular API
 * Some(uuid) for patients created via Excel import
 */
temp_id?: string | null; 
/**
 * Tracking fields for procedure defaults
 * Updated when new procedures are created, used to pre-populate procedure form
 */
latest_procedure_type: string | null; latest_fund: string | null; latest_date: string; latest_procedure_amount: number | null }
/**
 * Patient candidate for batch import - semantically different from Patient (lacks ID, created_at)
 */
export type PatientCandidate = { temp_id: string; name: string | null; ssn: string | null }
/**
 * Validation result wraps candidate with validation outcome
 */
export type PatientValidationResult = { candidate: PatientCandidate; status: PatientValidationStatus; existing_id: string | null; error: string | null }
/**
 * Validation status for patient candidate
 */
export type PatientValidationStatus = "VALID" | "ALREADY_EXISTS" | "INVALID"
/**
 * Payment method for a healthcare procedure
 * 
 * Represents how a procedure payment was made, inferred from Excel import data:
 * - None: No payment information or no confirmed payment date (default)
 * - Cash: Electronic payment (ES code in Excel)
 * - Check: Check payment (CH code in Excel)
 * - BankCard: Credit/debit card payment (not currently in Excel imports, handled later)
 * - BankTransfer: Bank transfer (inferred when confirmed_payment_date exists but no explicit method)
 */
export type PaymentMethod = "NONE" | "CASH" | "CHECK" | "BANK_CARD" | "BANK_TRANSFER"
/**
 * Complete parse result for a PDF statement
 */
export type PdfParseResult = { 
/**
 * All procedure groups found in the document
 */
groups: PdfProcedureGroup[]; 
/**
 * Number of lines that could not be parsed
 */
unparsed_line_count: number; 
/**
 * Sample unparsed lines for debugging (max 5)
 */
unparsed_lines: string[] }
/**
 * A group of procedure lines paid by the same fund on the same date
 */
export type PdfProcedureGroup = { 
/**
 * Fund short label from data lines (e.g., "CPAM n° 931")
 */
fund_label: string; 
/**
 * Full fund description from the total line
 */
fund_full_name: string; 
/**
 * Payment date for this group
 */
payment_date: string; 
/**
 * Total amount stated in the PDF (millièmes)
 */
total_amount: number; 
/**
 * Whether the sum of line amounts matches the stated total
 */
is_total_valid: boolean; 
/**
 * Individual procedure lines in this group
 */
lines: NormalizedPdfLine[] }
/**
 * Healthcare Procedure aggregate root
 * 
 * Represents a healthcare procedure (service/procedure) record with foreign key references
 * to Patient, Fund, and Procedure Type. Uses soft-delete pattern.
 * 
 * Payment tracking:
 * - procedure_amount: Total amount charged/invoiced for the procedure (millièmes)
 * - actual_payment_amount: Amount actually paid/received from patient or fund (millièmes)
 * - confirmed_payment_date: When the payment was confirmed (from reconciliation)
 * - payment_method: How payment was made (Cash/Check/BankCard/BankTransfer/None)
 */
export type Procedure = { 
/**
 * Foreign key to Patient (required)
 */
patient_id: string; 
/**
 * Foreign key to AffiliatedFund (optional - procedure can exist without a fund)
 */
fund_id: string | null; 
/**
 * Foreign key to ProcedureType (required)
 */
procedure_type_id: string; 
/**
 * Procedure date (required, ISO format: YYYY-MM-DD)
 */
procedure_date: string; 
/**
 * Total amount charged/invoiced for this procedure, in millièmes (e.g. 1234 = 1.234 €)
 * Optional - uses procedure type default amount if not specified
 * Source: Excel import column F or manual entry
 */
procedure_amount: number | null; 
/**
 * Payment method used for this procedure
 * Determines how payment was made: Cash/Check/BankCard/BankTransfer/None
 * - Cash: Electronic payment (ES in Excel)
 * - Check: Check payment (CH in Excel)
 * - BankCard: Credit/debit card (available for future use)
 * - BankTransfer: Inferred from confirmed_payment_date during reconciliation
 * - None: No payment information or no confirmed payment date
 */
payment_method: PaymentMethod; 
/**
 * Procedure status in the reconciliation lifecycle
 * Tracks progress through: None → Created → Reconciliated → FundPayed (or DirectlyPayed)
 * - None: Initial state
 * - Created: Procedure created, awaiting reconciliation
 * - Reconciliated: Associated with a fund payment group
 * - DirectlyPayed: Paid directly (cash/card), no fund reconciliation
 * - FundPayed: Bank payment matched via fund reconciliation
 */
payment_status: ProcedureStatus; 
/**
 * Date when payment was confirmed (ISO format: YYYY-MM-DD)
 * Source: Excel import column J or PDF reconciliation data
 * Presence of this date triggers BankTransfer inference if payment_method not explicit
 */
confirmed_payment_date: string; 
/**
 * Actual amount paid/received from patient or fund, in millièmes (e.g. 1234 = 1.234 €)
 * May differ from procedure_amount (partial payment, overpayment, etc.)
 * Source: Excel import column K or reconciliation statement
 */
actual_payment_amount: number | null; 
/**
 * Metadata - not a domain property
 */
id: string }
/**
 * Candidate procedure for batch creation and validation for orchestrators
 */
export type ProcedureCandidate = { patient_id: string; fund_id: string | null; procedure_type_id: string; procedure_date: string; procedure_amount: number | null; payment_method: string | null; confirmed_payment_date: string | null; actual_payment_amount: number | null; awaited_amount: number | null }
/**
 * Procedure status lifecycle
 * 
 * Represents the reconciliation state of a healthcare procedure:
 * - None: Initial state, no reconciliation activity
 * - Created: Procedure has been created and is awaiting payment/reconciliation
 * - Reconciliated: A fund payment group has been associated with this procedure
 * - DirectlyPayed: Procedure was paid directly (cash/card) without fund reconciliation (blocking re-import)
 * - FundPayed: A bank payment has been matched/reconciled with this procedure via fund (blocking re-import)
 * - ImportDirectlyPayed: From Excel import — paid directly (ES/CH), non-blocking re-import
 * - ImportFundPayed: From Excel import — fund present, method not ES/CH (non-blocking re-import)
 */
export type ProcedureStatus = "NONE" | "CREATED" | "RECONCILIATED" | 
/**
 * Fund reconciliation done but amount disputed: actual_payment_amount ≠ procedure_amount
 */
"PARTIALLY_RECONCILED" | "DIRECTLY_PAYED" | "FUND_PAYED" | 
/**
 * Bank transfer confirmed for a partially reconciled procedure
 */
"PARTIALLY_FUND_PAYED" | "IMPORT_DIRECTLY_PAYED" | "IMPORT_FUND_PAYED"
/**
 * Procedure Type aggregate root
 * 
 * Represents a type of healthcare service or procedure with a standard name and default amount.
 * Used to categorize procedures and provide default financial amounts.
 */
export type ProcedureType = { name: string; default_amount: number; category: string | null; 
/**
 * Metadata - not a domain property
 */
id: string }
/**
 * Result of validating a procedure candidate
 */
export type ProcedureValidationResult = { candidate: ProcedureCandidate; status: ProcedureValidationStatus; error: string | null }
/**
 * Validation status for a procedure candidate
 */
export type ProcedureValidationStatus = "VALID" | "INVALID"
/**
 * Raw healthcare procedure data from frontend (unvalidated)
 * Used for updating an existing procedure with data from an external source
 */
export type RawProcedure = { id: string; patient_id: string; fund_id: string | null; procedure_type_id: string; procedure_date: string; procedure_amount: number | null; payment_method: string | null; confirmed_payment_date: string | null; actual_payment_amount: number | null; payment_status: string }
/**
 * Raw procedure type data from frontend (unvalidated)
 */
export type RawProcedureType = { id: string; name: string; default_amount: number; category: string | null }
/**
 * Response from PDF reconciliation workflow
 */
export type ReconcileAndCandidatesResponse = { 
/**
 * Grouped payment candidates ready for user validation
 */
candidates: FundPaymentGroupCandidate[]; 
/**
 * Raw reconciliation details for reference
 */
reconciliation: ReconciliationResult }
/**
 * A reconciliation match result (unified discriminated union for all scenarios)
 */
export type ReconciliationMatch = 
/**
 * PDF line matched perfectly to one DB procedure (no anomalies)
 */
{ type: "PerfectSingleMatch"; data: { pdf_line: NormalizedPdfLine; db_match: DbMatch } } | 
/**
 * PDF line matched perfectly to multiple DB procedures (no anomalies)
 */
{ type: "PerfectGroupMatch"; data: { pdf_line: NormalizedPdfLine; db_matches: DbMatch[] } } | 
/**
 * PDF line matched to one DB procedure with anomalies
 */
{ type: "SingleMatchIssue"; data: { pdf_line: NormalizedPdfLine; db_match: DbMatch } } | 
/**
 * PDF line matched to multiple DB procedures with anomalies
 */
{ type: "GroupMatchIssue"; data: { pdf_line: NormalizedPdfLine; db_matches: DbMatch[] } } | 
/**
 * Too many procedures found for a single PDF line (above threshold, unresolvable)
 */
{ type: "TooManyMatchIssue"; data: { pdf_line: NormalizedPdfLine; candidate_ids: string[] } } | 
/**
 * PDF line not found in database; nearby_candidates are unreconciled procedures within ±1 day
 */
{ type: "NotFoundIssue"; data: { pdf_line: NormalizedPdfLine; nearby_candidates: NotFoundCandidate[] } }
/**
 * Complete reconciliation result structured as unified matches
 */
export type ReconciliationResult = { 
/**
 * Unified array of all reconciliation matches (perfect + issues)
 */
matches: ReconciliationMatch[] }
/**
 * A credit line that has been resolved with a fund ID
 */
export type ResolvedCreditLine = { date: string; label: string; amount: number; fund_id: string }
/**
 * Request to save or update a single amount → procedure type mapping
 */
export type SaveExcelAmountMappingRequest = { amount: number; procedure_type_id: string }
/**
 * Request to save label mappings
 */
export type SaveLabelMappingRequest = { bank_label: string; fund_id: string }
/**
 * Information about a skipped row during parsing
 */
export type SkippedRow = { sheet: string; row_number: number; reason: string }
/**
 * An unreconciled procedure for the post-reconciliation report
 */
export type UnreconciledProcedure = { procedure_id: string; patient_name: string; ssn: string; procedure_date: string; amount: number }
/**
 * Complex response: validation results
 */
export type ValidateBatchFundsResponse = { results: FundValidationResult[] }
/**
 * Complex response: validation results
 */
export type ValidateBatchPatientsResponse = { results: PatientValidationResult[] }
/**
 * Response DTO for procedure batch validation
 */
export type ValidateBatchProceduresResponse = { results: ProcedureValidationResult[] }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
